/**
 * Data for 16 recipe pages.
 * Each renders via RecipePage template + app/recipes-book/[slug]/page.tsx.
 *
 * Critical fix: existing /recipes-book/grilled-fish-salad.php has WRONG H1
 * ("Green Curd Salad") on the live site — corrected here per user authorisation.
 *
 * Each recipe gets full Recipe schema for Google Recipe carousel eligibility
 * (zero recipes currently have this — major free-traffic opportunity).
 */

export type RecipeCategory = "snack" | "dessert" | "beverage" | "soup" | "salad";

export type RecipeData = {
  slug: string;
  phpPath: string;
  name: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  heroImage: string;
  category: RecipeCategory;
  prepTime: string;       // ISO 8601 (PT15M = 15 min) — for Schema.org
  cookTime: string;
  totalTime: string;
  servings: number;
  description: string;     // brief intro
  benefits: string[];      // 3-5 nutritional/health benefits
  whoFor: string[];        // who would benefit most
  ingredients: string[];   // listed individually
  instructions: string[];  // step-by-step
  tips: string[];          // optional dietitian tips
  nutritionPerServing: {
    calories: string;
    protein: string;
    carbs: string;
    fat: string;
    fiber: string;
  };
  relatedConditions: string[]; // condition slugs that benefit from this recipe (internal links)
};

export const RECIPES: Record<string, RecipeData> = {
  "soya-granules-cutlet": {
    slug: "soya-granules-cutlet",
    phpPath: "/recipes-book/soya-granules-cutlet.php",
    name: "Soya Granules Cutlet",
    h1: "Soya Granules Cutlet — High Protein Vegetarian Snack",
    metaTitle: "Soya Granule Cutlet Recipe With Rich in Protein & Fibre - Go Moringa",
    metaDescription: "High-protein soya granule cutlet recipe by Go Moringa — easy snack rich in fibre, ideal for weight loss, PCOS, vegetarian protein needs.",
    heroImage: "/assets/receipe/soya-granules-cutlet.png",
    category: "snack",
    prepTime: "PT15M",
    cookTime: "PT15M",
    totalTime: "PT30M",
    servings: 4,
    description: "A high-protein, fibre-rich vegetarian snack made with soya granules, vegetables, and aromatic spices. Pan-fried with minimal oil — a guilt-free evening snack for weight watchers and a complete protein source for vegetarians.",
    benefits: [
      "High-quality plant protein (soya provides complete amino acid profile)",
      "Rich in dietary fibre — keeps you full longer",
      "Low glycaemic index — won't spike blood sugar",
      "Heart-healthy when pan-fried with minimal oil",
      "Suitable for weight loss, PCOS, and diabetic diets",
    ],
    whoFor: [
      "Vegetarians needing higher protein intake",
      "Weight loss clients looking for satisfying snacks",
      "PCOS clients (low-GI, high-fibre)",
      "Active adults needing post-workout snack",
    ],
    ingredients: [
      "1 cup soya granules (soaked in hot water for 15 min, squeezed dry)",
      "1 medium boiled potato, mashed",
      "1 small onion, finely chopped",
      "1 small carrot, grated",
      "2 tbsp green peas",
      "1 green chilli, finely chopped",
      "1 tsp ginger-garlic paste",
      "1/2 tsp cumin powder",
      "1/2 tsp coriander powder",
      "1/4 tsp turmeric powder",
      "1/2 tsp garam masala",
      "Salt to taste",
      "2 tbsp besan (chickpea flour) for binding",
      "Fresh coriander, chopped",
      "1-2 tbsp oil for shallow frying",
    ],
    instructions: [
      "Soak soya granules in hot water for 15 minutes, then squeeze out excess water completely.",
      "In a large bowl, combine soaked soya granules with mashed potato, onion, carrot, peas, green chilli, and ginger-garlic paste.",
      "Add all spices, salt, and fresh coriander. Mix well.",
      "Add besan gradually and knead into a firm dough. Adjust besan as needed for binding.",
      "Shape into round or oval cutlets, about 1 cm thick.",
      "Heat oil in a non-stick pan over medium heat. Shallow-fry cutlets for 3-4 minutes on each side until golden brown.",
      "Drain on paper towel. Serve hot with green chutney or low-fat curd.",
    ],
    tips: [
      "For air-fryer version: brush with oil and air-fry at 180°C for 12 minutes, flipping halfway.",
      "To make it diabetic-friendly, replace potato with boiled lauki or grated cabbage.",
      "Cutlets can be frozen uncooked for up to 1 month.",
    ],
    nutritionPerServing: {
      calories: "180 kcal",
      protein: "14 g",
      carbs: "22 g",
      fat: "5 g",
      fiber: "5 g",
    },
    relatedConditions: ["pcod-pcos", "diabetes"],
  },

  "kumbh-shaslik": {
    slug: "kumbh-shaslik",
    phpPath: "/recipes-book/kumbh-shaslik.php",
    name: "Kumbh Shashlik",
    h1: "Kumbh Shashlik — Healthy Mushroom Skewers",
    metaTitle: "Kumbh Shashlik - Healthy Snack For Vegetarians | Go Moringa",
    metaDescription: "Kumbh (mushroom) shashlik recipe by Go Moringa — grilled vegetarian skewers, low-calorie, high in B vitamins and antioxidants.",
    heroImage: "/assets/receipe/kumbh-shaslik.png",
    category: "snack",
    prepTime: "PT20M",
    cookTime: "PT15M",
    totalTime: "PT35M",
    servings: 3,
    description: "Marinated mushroom and vegetable skewers grilled to perfection — a sophisticated, low-calorie snack that's high in B vitamins, selenium, and antioxidants. Perfect for entertaining or as a guilt-free evening snack.",
    benefits: [
      "Very low calorie (mushrooms are 90% water)",
      "High in B vitamins (B2, B3, B5, folate)",
      "Selenium-rich — supports thyroid and immune function",
      "Plant antioxidants — anti-inflammatory benefits",
      "Suitable for weight loss and PCOS diets",
    ],
    whoFor: [
      "Weight loss clients looking for satisfying low-calorie snacks",
      "Thyroid clients (selenium support)",
      "PCOS clients (low-GI, anti-inflammatory)",
      "Diabetics (very low carb)",
    ],
    ingredients: [
      "250g button mushrooms, whole or halved",
      "1 capsicum (green or coloured), cubed",
      "1 onion, cut into chunks",
      "8-10 cherry tomatoes",
      "2 tbsp curd (yogurt)",
      "1 tsp ginger-garlic paste",
      "1 tsp tandoori masala",
      "1/2 tsp red chilli powder",
      "1/4 tsp turmeric powder",
      "1 tsp lemon juice",
      "1 tsp olive oil",
      "Salt to taste",
      "Wooden or metal skewers",
    ],
    instructions: [
      "In a bowl, whisk curd with ginger-garlic paste, all spices, lemon juice, oil, and salt.",
      "Add mushrooms and vegetables. Toss to coat thoroughly. Marinate for 20 minutes (or up to 2 hours).",
      "If using wooden skewers, soak in water for 10 minutes to prevent burning.",
      "Thread alternating mushrooms, capsicum, onion, and cherry tomatoes onto skewers.",
      "Grill on a hot tawa, grill pan, or oven (200°C) for 12-15 minutes, turning every 3-4 minutes until vegetables are tender and slightly charred.",
      "Brush with remaining marinade while grilling for extra flavour.",
      "Serve hot with mint chutney and lemon wedges.",
    ],
    tips: [
      "For an air-fryer version: 180°C for 12 minutes, shaking the basket halfway.",
      "Add paneer cubes for additional protein if needed.",
      "Best served immediately — mushrooms release water if left.",
    ],
    nutritionPerServing: {
      calories: "95 kcal",
      protein: "5 g",
      carbs: "10 g",
      fat: "4 g",
      fiber: "3 g",
    },
    relatedConditions: ["thyroid", "pcod-pcos", "diabetes"],
  },

  "green-curd-salad": {
    slug: "green-curd-salad",
    phpPath: "/recipes-book/green-curd-salad.php",
    name: "Green Curd Salad",
    h1: "Green Curd Salad — Cooling Probiotic Side",
    metaTitle: "Green Curd Salad Recipe by Go Moringa — Cooling Probiotic Side",
    metaDescription: "Green curd salad recipe by Go Moringa — cooling, probiotic-rich Indian salad with mint, cucumber, and herbs. Aids digestion, supports gut health.",
    heroImage: "/assets/receipe/green-curd-salad.png",
    category: "salad",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 4,
    description: "A cooling, probiotic-rich Indian salad combining fresh curd with mint, coriander, cucumber, and gentle spices. An everyday gut-health booster that pairs beautifully with any Indian meal.",
    benefits: [
      "Probiotic curd supports gut microbiome",
      "Hydrating cucumber + cooling mint balance Indian meals",
      "Low calorie — adds volume without heavy calories",
      "Calcium and protein from curd",
      "Aids digestion when paired with heavy meals",
    ],
    whoFor: [
      "Everyone — daily Indian meal companion",
      "Constipation and digestive issues",
      "Hot weather hydration",
      "Weight loss as a meal extender",
    ],
    ingredients: [
      "1 cup fresh hung curd (or strained yogurt)",
      "1 cucumber, finely chopped",
      "1 small onion, finely chopped",
      "1 green chilli, finely chopped",
      "1/4 cup fresh coriander, chopped",
      "1/4 cup fresh mint leaves, chopped",
      "1/2 tsp roasted cumin powder",
      "1/4 tsp black salt",
      "Regular salt to taste",
      "1 tsp lemon juice",
      "A pinch of black pepper",
    ],
    instructions: [
      "Whisk the curd in a bowl until smooth.",
      "Add chopped cucumber, onion, green chilli, coriander, and mint.",
      "Sprinkle roasted cumin powder, black salt, regular salt, and black pepper.",
      "Add lemon juice and mix gently.",
      "Chill for 10 minutes before serving for best flavour.",
      "Serve cold as a side with any Indian meal.",
    ],
    tips: [
      "Use hung curd for thicker consistency or regular curd for a more raita-like texture.",
      "Add grated cucumber instead of chopped for a smoother texture.",
      "Can be made 2-3 hours ahead — flavours improve with time.",
    ],
    nutritionPerServing: {
      calories: "60 kcal",
      protein: "4 g",
      carbs: "6 g",
      fat: "2 g",
      fiber: "1 g",
    },
    relatedConditions: ["constipation"],
  },

  "orange-mix-fruit": {
    slug: "orange-mix-fruit",
    phpPath: "/recipes-book/orange-mix-fruit.php",
    name: "Orange Mix Fruity",
    h1: "Orange Mix Fruity — Vitamin C Dessert Bowl",
    metaTitle: "Orange Mix Fruity Recipe — Vitamin C Dessert | Go Moringa",
    metaDescription: "Orange and mixed fruit dessert by Go Moringa — vitamin C powerhouse, immunity booster, low-calorie healthy dessert option.",
    heroImage: "/assets/receipe/orange-mix-fruit.png",
    category: "dessert",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 4,
    description: "A vibrant fruit bowl combining orange segments with seasonal fruits and a light honey-lime drizzle. A vitamin C powerhouse that doubles as a guilt-free dessert — bright, refreshing, and immunity-boosting.",
    benefits: [
      "Very high vitamin C (immunity + iron absorption)",
      "Natural sugars from whole fruit, with fibre intact",
      "Anti-oxidant rich — flavonoids from citrus",
      "Low calorie, high satiety",
      "Hydrating — fruit content 80%+ water",
    ],
    whoFor: [
      "Anyone wanting a healthy dessert option",
      "Iron-deficient clients (vitamin C aids iron absorption)",
      "Children's snacks",
      "Pre-workout or afternoon energy snack",
    ],
    ingredients: [
      "2 large oranges, peeled and segmented",
      "1 apple, diced",
      "1 banana, sliced",
      "1/2 cup pomegranate seeds",
      "1/2 cup grapes (seedless), halved",
      "1 tbsp honey (or to taste)",
      "1 tsp lime juice",
      "A pinch of black salt",
      "Fresh mint leaves for garnish",
      "1 tbsp chopped almonds or walnuts",
    ],
    instructions: [
      "Wash and prepare all fruits. Drain the orange segments to remove excess juice.",
      "In a large bowl, combine orange segments, apple, banana, pomegranate, and grapes.",
      "Whisk honey, lime juice, and black salt in a small bowl. Pour over the fruits.",
      "Toss gently to coat all fruits evenly.",
      "Top with chopped nuts and mint leaves.",
      "Serve chilled or at room temperature.",
    ],
    tips: [
      "Substitute honey with maple syrup or skip altogether for diabetics.",
      "Use seasonal fruits — mango, strawberry, pear, papaya work well.",
      "Add a sprinkle of chaat masala for an Indian twist.",
    ],
    nutritionPerServing: {
      calories: "140 kcal",
      protein: "2 g",
      carbs: "32 g",
      fat: "2 g",
      fiber: "5 g",
    },
    relatedConditions: ["micronutrient-deficiency"],
  },

  "bread-halva": {
    slug: "bread-halva",
    phpPath: "/recipes-book/bread-halva.php",
    name: "Bread Halwa",
    h1: "Quick Bread Halwa — Healthy Indian Dessert",
    metaTitle: "Bread Halva Recipe by Go Moringa — Healthier Indian Dessert",
    metaDescription: "Healthier bread halwa recipe by Go Moringa — reduced ghee, jaggery instead of sugar, whole-wheat bread option for a guilt-free Indian dessert.",
    heroImage: "/assets/receipe/bread-halwa.png",
    category: "dessert",
    prepTime: "PT5M",
    cookTime: "PT20M",
    totalTime: "PT25M",
    servings: 4,
    description: "A healthier take on the classic Indian bread halwa — made with whole-wheat bread, jaggery instead of refined sugar, and minimal ghee. Satisfying enough for a festive occasion, light enough for everyday.",
    benefits: [
      "Whole-wheat bread provides more fibre than the traditional version",
      "Jaggery is mineral-rich (iron, potassium, magnesium)",
      "Lower in refined sugar than traditional halwa",
      "Quick to prepare — under 30 minutes",
      "Portion-controlled satisfaction for sweet cravings",
    ],
    whoFor: [
      "Anyone craving Indian sweets without the heavy guilt",
      "Festival or special occasion sweets",
      "Iron-deficient clients (jaggery + tradition)",
      "Children's healthier dessert option",
    ],
    ingredients: [
      "6 slices whole-wheat bread, edges trimmed, cubed",
      "1.5 cups milk (low-fat)",
      "1/2 cup jaggery (powdered) — adjust to taste",
      "2 tbsp ghee",
      "1/4 tsp cardamom powder",
      "8-10 cashews, chopped",
      "8-10 almonds, slivered",
      "1 tbsp raisins",
      "A few saffron strands (optional)",
    ],
    instructions: [
      "Cut bread into small cubes after trimming the edges.",
      "Heat 1 tbsp ghee in a pan. Roast cashews, almonds, and raisins until golden. Remove and set aside.",
      "In the same pan, add remaining ghee. Add bread cubes. Roast on low-medium heat for 5-7 minutes until golden brown and crispy.",
      "Add milk and stir continuously. The bread will absorb the milk and start breaking down.",
      "Add jaggery powder. Stir until completely dissolved and the mixture thickens (about 5-7 minutes).",
      "Add cardamom powder and saffron. Mix well.",
      "Garnish with roasted nuts and raisins. Serve warm.",
    ],
    tips: [
      "Use multigrain bread for even more fibre.",
      "Replace jaggery with date paste for a sugar-free version.",
      "Add grated coconut for extra texture and healthy fats.",
    ],
    nutritionPerServing: {
      calories: "220 kcal",
      protein: "6 g",
      carbs: "32 g",
      fat: "8 g",
      fiber: "3 g",
    },
    relatedConditions: ["micronutrient-deficiency"],
  },

  "strawberry-yoghurt": {
    slug: "strawberry-yoghurt",
    phpPath: "/recipes-book/strawberry-yoghurt.php",
    name: "Strawberry Yoghurt",
    h1: "Strawberry Yoghurt — High Protein Healthy Dessert",
    metaTitle: "Strawberry Yogurt Recipe - Healthy Dessert With Rich Proteins - Go Moringa",
    metaDescription: "Strawberry yogurt recipe by Go Moringa — high protein, low calorie, gut-friendly dessert. Probiotic-rich with antioxidants from strawberries.",
    heroImage: "/assets/receipe/strawberry-yogurt.png",
    category: "dessert",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 2,
    description: "A protein-rich, probiotic dessert made with thick Greek-style hung curd, fresh strawberries, and natural sweetness. Perfect for guilt-free dessert cravings or as a post-workout snack.",
    benefits: [
      "High protein (12g+ per serving from Greek-style curd)",
      "Probiotic — supports gut microbiome",
      "Vitamin C and anthocyanins from strawberries",
      "Low calorie compared to traditional desserts",
      "Suitable for weight loss and post-workout recovery",
    ],
    whoFor: [
      "Weight loss clients with sweet cravings",
      "Post-workout protein needs",
      "Gut health and probiotic focus",
      "Children's healthier dessert",
    ],
    ingredients: [
      "1.5 cups hung curd (thick Greek-style yogurt)",
      "1 cup fresh strawberries, hulled and chopped (+ a few for garnish)",
      "1-2 tbsp honey or maple syrup (adjust)",
      "1/2 tsp vanilla extract (optional)",
      "1 tbsp chia seeds (optional, for extra fibre)",
      "A pinch of cardamom powder",
      "Crushed almonds for topping",
    ],
    instructions: [
      "If using regular curd, strain it through muslin cloth for 30 minutes to remove excess whey.",
      "Set aside a few whole strawberries for garnish. Mash the rest with a fork, or pulse briefly in a blender for a smoother texture.",
      "In a bowl, whisk hung curd until smooth.",
      "Add the mashed strawberries, honey, vanilla, and cardamom powder. Mix gently to maintain swirls of strawberry.",
      "If using chia seeds, fold them in. Let sit for 5 minutes for chia to soften.",
      "Divide into serving bowls. Top with sliced fresh strawberries and crushed almonds.",
      "Chill for 15-20 minutes before serving.",
    ],
    tips: [
      "Use frozen strawberries when fresh aren't available — thaw and drain first.",
      "For zero added sugar version, use 2-3 chopped dates instead of honey.",
      "Substitute with blueberries, raspberries, or any seasonal berry.",
    ],
    nutritionPerServing: {
      calories: "160 kcal",
      protein: "14 g",
      carbs: "20 g",
      fat: "3 g",
      fiber: "3 g",
    },
    relatedConditions: ["pcod-pcos", "constipation"],
  },

  "amla-juice-sharbat": {
    slug: "amla-juice-sharbat",
    phpPath: "/recipes-book/amla-juice-sharbat.php",
    name: "Amla Juice Sharbat",
    h1: "Amla Juice Sharbat — Vitamin C Powerhouse",
    metaTitle: "Amla Juice Sharbat Recipe by Go Moringa — Immunity Booster",
    metaDescription: "Amla juice sharbat recipe by Go Moringa — natural vitamin C powerhouse, immunity-boosting, supports liver and skin health.",
    heroImage: "/assets/receipe/amla-juice-sarbat.png",
    category: "beverage",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 4,
    description: "A traditional Indian immunity-booster — amla (Indian gooseberry) juice with honey, ginger, and a hint of black salt. One of the highest natural sources of vitamin C, taken regularly for skin, hair, and overall vitality.",
    benefits: [
      "Highest natural vitamin C — supports immunity",
      "Liver detoxification support",
      "Skin and hair health (vitamin C for collagen)",
      "Anti-inflammatory and antioxidant",
      "Supports thyroid function (some evidence)",
    ],
    whoFor: [
      "Daily immunity routine",
      "Iron-deficient clients (aids absorption)",
      "Skin and hair concerns",
      "Diabetics (helps glucose control)",
    ],
    ingredients: [
      "4-5 fresh amla (or 2 tbsp amla juice concentrate)",
      "1 inch piece of ginger",
      "1 tbsp honey",
      "A pinch of black salt",
      "1/2 tsp lemon juice",
      "Cold water as needed",
      "A few mint leaves for garnish",
    ],
    instructions: [
      "Wash amla, deseed, and chop roughly.",
      "Blend with ginger and a little water until smooth.",
      "Strain through a fine sieve into a glass.",
      "Add honey, black salt, and lemon juice. Whisk to combine.",
      "Top with cold water as desired.",
      "Garnish with mint leaves and serve immediately.",
    ],
    tips: [
      "Best consumed on an empty stomach in the morning.",
      "Diabetics can skip honey or replace with 2-3 drops of stevia.",
      "Bottled amla juice (without added sugar) works if fresh amla isn't available.",
    ],
    nutritionPerServing: {
      calories: "30 kcal",
      protein: "0.5 g",
      carbs: "7 g",
      fat: "0 g",
      fiber: "2 g",
    },
    relatedConditions: ["diabetes", "micronutrient-deficiency", "thyroid"],
  },

  "bael-squash": {
    slug: "bael-squash",
    phpPath: "/recipes-book/bael-squash.php",
    name: "Bael Squash",
    h1: "Bael Squash — Cooling Summer Drink",
    metaTitle: "Bael Squash Recipe by Go Moringa — Cooling Summer Drink",
    metaDescription: "Bael squash recipe by Go Moringa — traditional Indian cooling drink with anti-inflammatory and digestive benefits. Perfect for summer.",
    heroImage: "/assets/receipe/bael-squash-beverage.png",
    category: "beverage",
    prepTime: "PT15M",
    cookTime: "PT0M",
    totalTime: "PT15M",
    servings: 4,
    description: "Bael fruit (wood apple) squash is a traditional Indian summer drink with powerful anti-inflammatory and digestive benefits. Cooling, hydrating, and naturally sweet — a far better choice than packaged summer drinks.",
    benefits: [
      "Anti-inflammatory — soothes digestive tract",
      "Cooling — body-temperature regulation in summer",
      "Hydrating with natural electrolytes",
      "Supports gut health and bowel regularity",
      "Liver-friendly",
    ],
    whoFor: [
      "Summer hydration for everyone",
      "Constipation and gut issues",
      "Acidity and reflux sufferers",
      "Children (gentle on the stomach)",
    ],
    ingredients: [
      "1 ripe bael fruit (or 4 tbsp bael pulp concentrate)",
      "4 cups cold water",
      "2-3 tbsp honey or jaggery (to taste)",
      "1 tsp lemon juice",
      "A pinch of black salt",
      "A pinch of roasted cumin powder",
      "Ice cubes",
      "Mint leaves for garnish",
    ],
    instructions: [
      "Break open the bael fruit and scoop out the pulp.",
      "Mix the pulp with 1 cup water and mash with your hands or a wooden masher to break it down.",
      "Strain through a fine sieve, pressing the pulp to extract all the juice.",
      "Discard the fibrous residue and seeds.",
      "Add remaining cold water to the strained juice.",
      "Stir in honey/jaggery, lemon juice, black salt, and roasted cumin powder.",
      "Add ice cubes, garnish with mint, and serve immediately.",
    ],
    tips: [
      "Look for ripe bael in summer at any Indian grocery store.",
      "Sugar can be omitted for diabetics — ripe bael has natural sweetness.",
      "For gut issues, drink at room temperature instead of chilled.",
    ],
    nutritionPerServing: {
      calories: "60 kcal",
      protein: "1 g",
      carbs: "15 g",
      fat: "0 g",
      fiber: "2 g",
    },
    relatedConditions: ["constipation", "depression"],
  },

  "beetroot-chaas": {
    slug: "beetroot-chaas",
    phpPath: "/recipes-book/beetroot-chaas.php",
    name: "Beetroot Chaas",
    h1: "Beetroot Chaas — BP-Lowering Probiotic Drink",
    metaTitle: "Beetroot Chaas Recipe by Go Moringa — BP-Lowering Probiotic Drink",
    metaDescription: "Beetroot chaas recipe by Go Moringa — combines BP-lowering beetroot with probiotic buttermilk. Heart-healthy, refreshing, and gut-friendly.",
    heroImage: "/assets/receipe/beetroot-chaas.png",
    category: "beverage",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 4,
    description: "A creative spin on traditional chaas (buttermilk) — combines BP-lowering beetroot with probiotic buttermilk and digestive spices. Studies show beetroot can lower systolic BP by 4-10 mmHg; chaas adds gut health and cooling.",
    benefits: [
      "Beetroot lowers blood pressure (nitric oxide pathway)",
      "Probiotic gut support from buttermilk",
      "Iron-rich — supports iron-deficient clients",
      "Hydrating — adds electrolytes",
      "Low calorie, high satiety",
    ],
    whoFor: [
      "Hypertension clients",
      "Iron-deficient women",
      "Anyone needing cooling probiotic drink",
      "Summer hydration",
    ],
    ingredients: [
      "1 medium beetroot, peeled and roughly chopped",
      "1.5 cups thick curd (yogurt)",
      "1.5 cups cold water",
      "1/2 tsp roasted cumin powder",
      "1/4 tsp black salt",
      "1/4 tsp ginger powder (or grated fresh ginger)",
      "1 green chilli, optional",
      "Fresh coriander, chopped",
      "Mint leaves for garnish",
      "Salt to taste",
    ],
    instructions: [
      "Boil or steam the chopped beetroot until tender (about 15 minutes). Cool.",
      "Blend cooked beetroot to a smooth puree.",
      "In a large jar, whisk curd with cold water until thin and smooth.",
      "Add beetroot puree, roasted cumin powder, black salt, ginger, and green chilli.",
      "Whisk or blend everything together for 30 seconds.",
      "Add coriander and mix.",
      "Serve chilled, garnished with mint leaves.",
    ],
    tips: [
      "Use cooked beetroot — raw has stronger earthy flavour some find off-putting.",
      "For darker colour and stronger BP effect, use more beetroot.",
      "Make ahead and refrigerate for up to 1 day.",
    ],
    nutritionPerServing: {
      calories: "80 kcal",
      protein: "4 g",
      carbs: "12 g",
      fat: "1 g",
      fiber: "2 g",
    },
    relatedConditions: ["high-blood-pressure", "heart-disease", "micronutrient-deficiency"],
  },

  "green-energizer-juice": {
    slug: "green-energizer-juice",
    phpPath: "/recipes-book/green-energizer-juice.php",
    name: "Green Energizer Juice",
    h1: "Green Energizer Juice — Morning Detox Drink",
    metaTitle: "Green Energizer Juice Recipe By Dt. Priyatama Srivastava in Gurugram",
    metaDescription: "Green energizer juice by Go Moringa — spinach, cucumber, apple, ginger detox drink. Energy boost, liver support, weight loss friendly.",
    heroImage: "/assets/receipe/green-energize-juice.png",
    category: "beverage",
    prepTime: "PT10M",
    cookTime: "PT0M",
    totalTime: "PT10M",
    servings: 2,
    description: "A morning energy-boosting green juice combining spinach, cucumber, apple, lemon, and ginger. Rich in chlorophyll, antioxidants, and natural enzymes — gentle on the stomach and energising without caffeine.",
    benefits: [
      "Energy boost from natural sugars + chlorophyll",
      "Liver detoxification support",
      "Iron + folate from spinach",
      "Hydrating with electrolytes",
      "Weight loss friendly (low calorie, high satiety)",
    ],
    whoFor: [
      "Morning energy routine",
      "Iron-deficient clients",
      "Weight loss programs",
      "Anyone wanting a caffeine-free energy boost",
    ],
    ingredients: [
      "2 cups fresh spinach",
      "1 cucumber, roughly chopped",
      "1 green apple, cored and chopped",
      "1 inch ginger",
      "1 lemon, juiced",
      "1 cup cold water (or coconut water)",
      "A pinch of black salt",
      "Ice cubes",
    ],
    instructions: [
      "Wash spinach thoroughly. Roughly chop cucumber and apple.",
      "Add spinach, cucumber, apple, and ginger to a blender.",
      "Add water and blend for 60-90 seconds until smooth.",
      "Strain through a fine sieve or nut milk bag for smoother juice (optional — skip if you want full fibre).",
      "Stir in lemon juice and black salt.",
      "Pour into glasses with ice cubes and serve immediately.",
    ],
    tips: [
      "Drink within 15 minutes of preparation for maximum nutrient retention.",
      "For diabetics: skip the apple, add cucumber, and use stevia if sweetness needed.",
      "Add 1 tsp chia seeds for extra omega-3 and fibre.",
    ],
    nutritionPerServing: {
      calories: "100 kcal",
      protein: "3 g",
      carbs: "22 g",
      fat: "0 g",
      fiber: "4 g",
    },
    relatedConditions: ["micronutrient-deficiency"],
  },

  "celery-soup": {
    slug: "celery-soup",
    phpPath: "/recipes-book/celery-soup.php",
    name: "Celery Soup",
    h1: "Celery Soup — Low Calorie Anti-Inflammatory Bowl",
    metaTitle: "Celery Soup Recipe by Go Moringa — Anti-Inflammatory Bowl",
    metaDescription: "Celery soup recipe by Go Moringa — low calorie, anti-inflammatory, BP-friendly soup. Great for weight loss, hypertension, edema, gout.",
    heroImage: "/assets/receipe/celery-soup.png",
    category: "soup",
    prepTime: "PT10M",
    cookTime: "PT20M",
    totalTime: "PT30M",
    servings: 4,
    description: "A light, low-calorie celery soup with subtle herbs — naturally diuretic (helps water retention), anti-inflammatory, and BP-friendly. A satisfying starter for weight-loss meals or a soothing bowl during illness recovery.",
    benefits: [
      "Very low calorie (under 60 per serving)",
      "Natural diuretic — helps water retention",
      "Anti-inflammatory — supports gout, arthritis",
      "BP-friendly (potassium-rich, low sodium when made unsalted)",
      "Hydrating and satisfying",
    ],
    whoFor: [
      "Weight loss clients",
      "Water retention / edema",
      "Hypertension",
      "Gout flare recovery",
      "Post-illness gentle nutrition",
    ],
    ingredients: [
      "4 large celery stalks with leaves, chopped",
      "1 medium onion, chopped",
      "2 cloves garlic, minced",
      "1 medium potato, peeled and cubed (optional, for thickness)",
      "4 cups low-sodium vegetable stock (or water)",
      "1 tsp olive oil",
      "1/2 tsp dried thyme or fresh thyme leaves",
      "1 bay leaf",
      "Salt to taste (use sparingly)",
      "Black pepper to taste",
      "Fresh parsley for garnish",
      "A splash of lemon juice (optional)",
    ],
    instructions: [
      "Heat olive oil in a pot. Sauté onion and garlic until soft and translucent (3-4 min).",
      "Add chopped celery (reserving some leaves for garnish). Sauté for 5 minutes.",
      "Add potato cubes, vegetable stock, thyme, and bay leaf.",
      "Bring to a boil, then simmer for 15-20 minutes until celery and potato are very tender.",
      "Remove bay leaf. Blend the soup with an immersion blender (or in batches in a regular blender) until smooth.",
      "Season with salt and black pepper. Add a splash of lemon juice for brightness.",
      "Garnish with reserved celery leaves and fresh parsley. Serve hot.",
    ],
    tips: [
      "Add a small amount of low-fat cream or coconut milk for richness — skip for weight loss.",
      "For higher protein, blend in 1/2 cup white beans or tofu.",
      "Freezes well for up to 1 month.",
    ],
    nutritionPerServing: {
      calories: "55 kcal",
      protein: "2 g",
      carbs: "10 g",
      fat: "1 g",
      fiber: "3 g",
    },
    relatedConditions: ["water-retention", "uric-acid", "high-blood-pressure"],
  },

  "vegetable-and-flaxseed-soup": {
    slug: "vegetable-and-flaxseed-soup",
    phpPath: "/recipes-book/vegetable-and-flaxseed-soup.php",
    name: "Vegetable and Flaxseed Soup",
    h1: "Vegetable & Flaxseed Soup — Omega-3 Rich Bowl",
    metaTitle: "Yummy Mix Vegetable and Flaxseed Soup Recipe | Go Moringa",
    metaDescription: "Vegetable and flaxseed soup recipe by Go Moringa — omega-3 rich, fibre-loaded, supports heart, gut, hormonal health.",
    heroImage: "/assets/receipe/celery-soup.png",
    category: "soup",
    prepTime: "PT15M",
    cookTime: "PT25M",
    totalTime: "PT40M",
    servings: 4,
    description: "A nutrient-dense mixed-vegetable soup boosted with ground flaxseed — providing omega-3 fatty acids, fibre, lignans, and a deep, satisfying flavour. Perfect for heart health, hormonal balance, and gut microbiome support.",
    benefits: [
      "Omega-3 fatty acids from flaxseed (heart + brain support)",
      "Lignans support hormonal balance",
      "High fibre — gut health + satiety",
      "Vegetable variety provides broad micronutrient profile",
      "Anti-inflammatory + cardiovascular protective",
    ],
    whoFor: [
      "Heart disease and cholesterol clients",
      "PCOS and hormonal balance",
      "Constipation and gut issues",
      "Weight loss programs",
    ],
    ingredients: [
      "2 cups mixed vegetables (carrot, beans, peas, capsicum, cauliflower), chopped",
      "1 medium onion, chopped",
      "2 cloves garlic, minced",
      "1 medium tomato, chopped",
      "2 tbsp ground flaxseed",
      "4 cups low-sodium vegetable stock or water",
      "1 tsp olive oil",
      "1/2 tsp cumin seeds",
      "1/2 tsp turmeric powder",
      "1/2 tsp black pepper",
      "Salt to taste",
      "Fresh coriander for garnish",
      "1 tsp lemon juice",
    ],
    instructions: [
      "Heat olive oil in a pot. Add cumin seeds and let them splutter.",
      "Add onion and garlic. Sauté until soft (3-4 min).",
      "Add tomato and turmeric. Cook for 2-3 minutes until tomato softens.",
      "Add mixed vegetables. Stir-fry for 5 minutes.",
      "Add vegetable stock and bring to a boil. Reduce heat and simmer for 15-20 minutes until vegetables are tender.",
      "Stir in ground flaxseed (add at the end to preserve omega-3).",
      "Season with salt and black pepper.",
      "Garnish with fresh coriander and a squeeze of lemon. Serve hot.",
    ],
    tips: [
      "Always grind flaxseed fresh — whole flaxseeds pass through digestion without absorption.",
      "Add cooked dal or beans for additional protein.",
      "For creamier texture, blend half the soup and return to the pot.",
    ],
    nutritionPerServing: {
      calories: "120 kcal",
      protein: "4 g",
      carbs: "16 g",
      fat: "5 g",
      fiber: "6 g",
    },
    relatedConditions: ["heart-disease", "pcod-pcos", "lipid-profile-cholesterol", "constipation"],
  },

  "easy-carrot-ginger-soup": {
    slug: "easy-carrot-ginger-soup",
    phpPath: "/recipes-book/easy-carrot-ginger-soup.php",
    name: "Easy Carrot Ginger Soup",
    h1: "Easy Carrot Ginger Soup — Immunity Booster Bowl",
    metaTitle: "Easy Carrot Ginger Soup Recipe by Go Moringa — Immunity Bowl",
    metaDescription: "Easy carrot ginger soup recipe by Go Moringa — immunity-boosting, vitamin A powerhouse, anti-inflammatory, perfect for cold seasons.",
    heroImage: "/assets/receipe/easy-carrot-ginger-soup.png",
    category: "soup",
    prepTime: "PT10M",
    cookTime: "PT25M",
    totalTime: "PT35M",
    servings: 4,
    description: "A warming, vitamin A-rich carrot soup with a punch of ginger — naturally sweet, deeply nourishing, and a classic immunity-supporter for cold seasons or recovery from illness.",
    benefits: [
      "Vitamin A from carrots — supports vision, skin, immunity",
      "Ginger anti-inflammatory and digestive benefits",
      "Naturally sweet without added sugar",
      "Low calorie, high satiety",
      "Easy on the stomach during illness recovery",
    ],
    whoFor: [
      "Cold/flu recovery",
      "Children (mildly sweet, vegetable-loaded)",
      "Skin health concerns",
      "Anyone needing a gentle dinner option",
    ],
    ingredients: [
      "5 medium carrots, peeled and chopped",
      "1 medium onion, chopped",
      "2 inches fresh ginger, peeled and chopped",
      "2 cloves garlic, minced",
      "4 cups vegetable stock",
      "1 tsp olive oil",
      "1/2 tsp ground coriander",
      "1/4 tsp ground cumin",
      "Salt and pepper to taste",
      "1 tbsp lemon juice",
      "Fresh coriander or parsley for garnish",
      "Optional: 2 tbsp coconut milk for creaminess",
    ],
    instructions: [
      "Heat olive oil in a pot. Sauté onion and garlic until soft (3-4 min).",
      "Add ginger and sauté for 30 seconds.",
      "Add carrots, ground coriander, and cumin. Stir for 2 minutes.",
      "Pour in vegetable stock. Bring to a boil, then simmer for 20 minutes until carrots are very tender.",
      "Use an immersion blender (or transfer to a blender in batches) to blend until smooth.",
      "Season with salt and pepper. Stir in lemon juice.",
      "If using, swirl in coconut milk for richness.",
      "Garnish with fresh coriander or parsley. Serve hot.",
    ],
    tips: [
      "Roast the carrots beforehand (200°C for 25 minutes) for deeper flavour.",
      "Add a small piece of turmeric for additional anti-inflammatory benefits.",
      "Freezes beautifully — make a double batch.",
    ],
    nutritionPerServing: {
      calories: "100 kcal",
      protein: "2 g",
      carbs: "20 g",
      fat: "2 g",
      fiber: "4 g",
    },
    relatedConditions: ["depression", "micronutrient-deficiency"],
  },

  "ginger-papaya-salsa": {
    slug: "ginger-papaya-salsa",
    phpPath: "/recipes-book/ginger-papaya-salsa.php",
    name: "Ginger Papaya Salsa",
    h1: "Ginger Papaya Salsa — Digestive Health Side",
    metaTitle: "Ginger Papaya Salsa Recipe by Go Moringa — Digestive Side",
    metaDescription: "Ginger papaya salsa recipe by Go Moringa — papaya enzymes + ginger for digestion. Refreshing tropical Indian fusion side.",
    heroImage: "/assets/receipe/ginger-papaya-salsa.png",
    category: "salad",
    prepTime: "PT15M",
    cookTime: "PT0M",
    totalTime: "PT15M",
    servings: 4,
    description: "A tropical-Indian fusion salsa combining ripe papaya with ginger, lime, and a touch of chilli. Papaya enzymes (papain) and ginger combine for a powerful digestive aid that doubles as a refreshing side or topping.",
    benefits: [
      "Papain enzyme aids protein digestion",
      "Ginger anti-inflammatory and anti-nausea",
      "Vitamin C and beta-carotene from papaya",
      "Low calorie, high nutritional density",
      "Cooling on a hot day",
    ],
    whoFor: [
      "Digestive issues, bloating, constipation",
      "Post-meal digestion aid for heavy eaters",
      "Skin health concerns",
      "Children (naturally sweet)",
    ],
    ingredients: [
      "2 cups ripe papaya, diced",
      "1/4 red onion, finely chopped",
      "1 inch fresh ginger, finely minced",
      "1/2 jalapeño or green chilli, minced (optional)",
      "1/4 cup fresh coriander, chopped",
      "Juice of 1 lime",
      "1 tbsp olive oil",
      "A pinch of black salt",
      "Regular salt to taste",
      "1/2 tsp roasted cumin powder",
      "Optional: 1 tbsp pumpkin seeds for crunch",
    ],
    instructions: [
      "Combine papaya, red onion, ginger, and chilli (if using) in a bowl.",
      "Add fresh coriander.",
      "Whisk lime juice, olive oil, black salt, regular salt, and roasted cumin in a small bowl.",
      "Pour dressing over papaya mixture and toss gently.",
      "Top with pumpkin seeds if using.",
      "Let rest for 5-10 minutes for flavours to meld. Serve cold.",
    ],
    tips: [
      "Use as a topping for grilled fish or chicken.",
      "Can also be served as a starter side with Indian meals.",
      "Add a small pinch of chaat masala for extra Indian flavour.",
    ],
    nutritionPerServing: {
      calories: "70 kcal",
      protein: "1 g",
      carbs: "13 g",
      fat: "2 g",
      fiber: "3 g",
    },
    relatedConditions: ["constipation"],
  },

  "grilled-fish-salad": {
    slug: "grilled-fish-salad",
    phpPath: "/recipes-book/grilled-fish-salad.php",
    name: "Grilled Fish Salad",
    h1: "Grilled Fish Salad — Lean Protein Power Bowl",
    metaTitle: "Grilled Fish Salad Recipe With Protein & Antioxidants - Go Moringa",
    metaDescription: "Grilled fish salad recipe by Go Moringa — lean protein, omega-3, antioxidant-rich. Perfect for weight loss, heart health, cardiac diets.",
    heroImage: "/assets/receipe/grilled-fish-salad-recipe.png",
    category: "salad",
    prepTime: "PT15M",
    cookTime: "PT15M",
    totalTime: "PT30M",
    servings: 2,
    description: "A balanced power-bowl combining grilled fish (rich in lean protein and omega-3) with a generous mix of crunchy greens, fresh vegetables, and a light dressing. Ideal for weight loss, cardiac health, and active adults needing high-quality protein.",
    benefits: [
      "Lean protein from fish (especially fatty fish like salmon, mackerel)",
      "Omega-3 fatty acids for heart and brain",
      "Antioxidants from mixed greens",
      "Low carb, high satiety",
      "Suitable for weight loss + cardiac diets",
    ],
    whoFor: [
      "Heart disease, cholesterol clients",
      "Weight loss programs",
      "Active adults needing post-workout meal",
      "Anyone wanting a complete protein meal",
    ],
    ingredients: [
      "200g fish fillet (salmon, basa, or any firm white fish)",
      "1 tsp olive oil",
      "1 tsp lemon juice for marinating",
      "1/2 tsp black pepper",
      "1/4 tsp turmeric",
      "1/2 tsp salt",
      "1 garlic clove, minced",
      "For the salad:",
      "4 cups mixed greens (lettuce, spinach, rocket)",
      "1 cucumber, sliced",
      "1 cup cherry tomatoes, halved",
      "1/2 red onion, thinly sliced",
      "1/2 avocado, sliced (optional)",
      "2 tbsp pumpkin seeds or walnuts",
      "For the dressing:",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "1 tsp Dijon mustard (or 1/2 tsp Indian mustard)",
      "Salt and pepper",
    ],
    instructions: [
      "Marinate fish with olive oil, lemon juice, black pepper, turmeric, salt, and garlic for 15 minutes.",
      "Heat a grill pan or non-stick skillet over medium-high heat. Grill fish for 3-4 minutes per side until cooked through.",
      "Meanwhile, prepare the salad: combine mixed greens, cucumber, tomatoes, red onion, and avocado in a large bowl.",
      "Whisk all dressing ingredients in a small bowl.",
      "Pour dressing over salad and toss gently.",
      "Divide salad onto two plates. Top with grilled fish.",
      "Sprinkle with pumpkin seeds or walnuts. Serve immediately.",
    ],
    tips: [
      "Choose wild-caught or sustainably-farmed fish where possible.",
      "Add quinoa or brown rice underneath for a heartier meal.",
      "Substitute fish with grilled chicken breast or paneer if vegetarian.",
    ],
    nutritionPerServing: {
      calories: "320 kcal",
      protein: "28 g",
      carbs: "12 g",
      fat: "18 g",
      fiber: "5 g",
    },
    relatedConditions: ["heart-disease", "lipid-profile-cholesterol", "diabetes"],
  },

  "kabuli-channa-salads": {
    slug: "kabuli-channa-salads",
    phpPath: "/recipes-book/kabuli-channa-salads.php",
    name: "Kabuli Chana Salad",
    h1: "Kabuli Chana Salad — High Protein Indian Bowl",
    metaTitle: "Kabuli Channa Salad Recipe by Go Moringa — High Protein Bowl",
    metaDescription: "Kabuli chana (chickpea) salad by Go Moringa — high protein, fibre-rich vegetarian salad. Great for weight loss, PCOS, vegetarian protein.",
    heroImage: "/assets/receipe/kabuli-channa-salads.png",
    category: "salad",
    prepTime: "PT15M",
    cookTime: "PT0M",
    totalTime: "PT15M",
    servings: 3,
    description: "A protein-packed Indian-style chickpea salad with fresh vegetables, herbs, and a tangy dressing. Filling, fibre-rich, and naturally low-glycaemic — perfect for vegetarians, PCOS clients, and weight watchers.",
    benefits: [
      "High plant protein (8g+ per serving)",
      "Low glycaemic index — steady energy",
      "High fibre — gut health and satiety",
      "Iron, folate, and magnesium",
      "Excellent for weight loss, PCOS, diabetes",
    ],
    whoFor: [
      "Vegetarians needing higher protein",
      "PCOS and diabetes clients",
      "Weight loss programs",
      "Office lunch boxes (travels well)",
    ],
    ingredients: [
      "2 cups boiled or canned kabuli chana (white chickpeas), drained",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 red onion, finely chopped",
      "1 capsicum, diced",
      "1/4 cup fresh coriander, chopped",
      "1/4 cup fresh mint, chopped",
      "1 green chilli, finely chopped (optional)",
      "For the dressing:",
      "2 tbsp olive oil",
      "Juice of 1 lemon",
      "1 tsp roasted cumin powder",
      "1/2 tsp black salt",
      "1/4 tsp red chilli powder",
      "1 tsp chaat masala",
      "Salt to taste",
    ],
    instructions: [
      "If using dry chickpeas, soak overnight and pressure cook for 4-5 whistles until tender. Drain and cool.",
      "In a large bowl, combine chickpeas with all chopped vegetables.",
      "Add fresh coriander, mint, and green chilli.",
      "Whisk all dressing ingredients in a small bowl.",
      "Pour dressing over salad and toss thoroughly.",
      "Let rest for 10 minutes for flavours to meld.",
      "Serve at room temperature or slightly chilled.",
    ],
    tips: [
      "Sprouted chickpeas have even higher nutrient density.",
      "Add chopped pomegranate for sweetness and antioxidants.",
      "Add crumbled feta or paneer for extra protein.",
    ],
    nutritionPerServing: {
      calories: "210 kcal",
      protein: "9 g",
      carbs: "30 g",
      fat: "7 g",
      fiber: "8 g",
    },
    relatedConditions: ["pcod-pcos", "diabetes", "metabolic-syndrome"],
  },
};

export const RECIPE_LIST = Object.values(RECIPES);

export function getRecipe(slug: string): RecipeData | undefined {
  return RECIPES[slug];
}

export function getRecipesByCategory(category: RecipeCategory): RecipeData[] {
  return RECIPE_LIST.filter((r) => r.category === category);
}
