/**
 * Data for all 20 treatment / condition pages.
 * Each renders via the TreatmentPage template + app/treatment/[slug]/page.tsx.
 * Current live site averages 265 words/page; we target 1,000+ with clinical depth.
 *
 * Indexed H1 typos in the current site are corrected here (Cushing's, Lipid Profile,
 * Certain Medicines, Treatment hub).
 */

import type { FAQ } from "./services";

export type TreatmentData = {
  slug: string;
  phpPath: string;
  title: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  heroImage: string;
  introLead: string;
  aboutCondition: string;
  howDietHelps: string;
  foodsToInclude: string[];
  foodsToAvoid: string[];
  sampleDay?: { meal: string; description: string }[];
  faqs: FAQ[];
  related: string[];
};

export const TREATMENTS: Record<string, TreatmentData> = {
  diabetes: {
    slug: "diabetes",
    phpPath: "/treatment/diabetes.php",
    title: "Diabetes",
    h1: "Diabetes Diet Plan in Gurgaon",
    metaTitle: "Best Diabetes Diet Plan in Gurgaon | Diabetic Dietitian | Go Moringa",
    metaDescription: "Diabetes diet plan by Go Moringa — Indian meal-based, low-glycemic protocol. Most clients see HbA1c drop 1-2 points in 4 months. 20 years experience.",
    heroImage: "/assets/treatment/diabetes.jpg",
    introLead: "Type 2 diabetes is one of the most diet-responsive chronic conditions we manage. With disciplined dietary intervention, most of our clients see their HbA1c drop by 1-2 percentage points within 4 months — and many reduce or eliminate medication entirely, under their physician's supervision.",
    aboutCondition: "Diabetes mellitus is a metabolic condition where the body either does not produce enough insulin (Type 1) or does not respond properly to insulin (Type 2). Type 2 accounts for over 90 percent of cases in India and is increasingly common in adults from their late 20s onwards. Symptoms include persistent fatigue, frequent urination, increased thirst, unexplained weight loss or gain, blurred vision, and slow wound healing. Left unmanaged, diabetes damages the kidneys, eyes, nerves, heart, and blood vessels. Pre-diabetes — fasting glucose 100-125 mg/dL or HbA1c 5.7-6.4 percent — is reversible in most cases through diet alone. India's diabetes rate is among the highest globally, with Gurgaon's corporate-heavy, sedentary, late-dinner culture being a contributing risk factor.",
    howDietHelps: "Diet works on diabetes through four mechanisms: (1) reducing the carbohydrate load at each meal so blood glucose does not spike, (2) improving insulin sensitivity through weight loss and anti-inflammatory eating, (3) stabilising glucose throughout the day via meal timing aligned with medication, and (4) addressing micronutrient deficiencies (magnesium, chromium, vitamin D) that worsen insulin resistance. Indian meal patterns work very well for diabetes management when portion-controlled and properly paired — rice with adequate dal, protein, and fibre has a very different glucose curve than rice alone. Our diabetes protocol is built around regular Indian eating, not foreign or restrictive diets.",
    foodsToInclude: [
      "Whole grains: bajra, jowar, ragi, brown rice, oats (portion-controlled)",
      "Lentils and dals (high fibre, protein)",
      "Non-starchy vegetables: leafy greens, lauki, tinda, ladyfinger, capsicum",
      "Pulses: chana, rajma, kala chana (with adequate soaking)",
      "Curd and paneer (in moderation)",
      "Nuts: almonds, walnuts, peanuts (small handful)",
      "Seeds: flaxseed, chia, methi seeds",
      "Bitter gourd (karela), fenugreek leaves",
      "Lean protein: eggs, chicken, fish (twice a week)",
      "Whole fruits in measured portion (jamun, guava, papaya prioritised)",
    ],
    foodsToAvoid: [
      "Refined sugar, jaggery in large amounts",
      "White rice in large portions (and biryani)",
      "Maida-based foods: bread, naan, pizza, biscuits",
      "Sweetened beverages: cola, packaged juice, sweetened lassi",
      "Fried snacks: samosa, kachori, pakora, namkeen",
      "Mithai and Indian sweets",
      "Honey, agave, 'natural' sweetener marketing",
      "Fruit juice (even fresh; eat the whole fruit instead)",
      "Sweetened breakfast cereals",
      "Late-night dinners (after 9 PM)",
    ],
    sampleDay: [
      { meal: "Early morning", description: "Methi water OR cinnamon water + 5 soaked almonds" },
      { meal: "Breakfast", description: "Vegetable besan chilla (2) + green chutney + 1 cup chai with toned milk, no sugar" },
      { meal: "Mid-morning", description: "1 small fruit (guava/papaya/orange) OR a handful of peanuts" },
      { meal: "Lunch", description: "2 phulka (no ghee) + 1 katori dal + 1 katori sabzi + salad + curd + 1 small bowl rice OPTIONAL" },
      { meal: "Tea time", description: "Roasted chana (small bowl) + 1 cup green tea" },
      { meal: "Dinner (by 8 PM)", description: "1 phulka + 1 katori sabzi (high vegetable) + 1 katori dal/paneer/chicken + salad" },
      { meal: "Bedtime", description: "1 cup haldi milk OR fenugreek tea (helps overnight glucose stability)" },
    ],
    faqs: [
      { q: "Can diet alone reverse my Type 2 diabetes?", a: "For early-stage Type 2 diabetes, full remission is possible with disciplined dietary intervention. Many of our clients have come off all diabetes medication while maintaining normal blood glucose — under their physician's supervision. For longer-standing diabetes, diet substantially reduces complications and medication needs even if full reversal is not realistic." },
      { q: "How quickly will I see results?", a: "HbA1c reflects 3-month average glucose, so the headline number takes about 3 months to show meaningful change. But daily glucose readings often improve within 1-2 weeks of disciplined eating. We track fasting glucose weekly, post-meal glucose twice weekly, and HbA1c every 3 months." },
      { q: "Will I have to give up rice and roti?", a: "No. Portions and pairings change — rice paired with adequate dal, protein, and fibre has a controlled glucose curve. Roti from atta (not maida) in measured portions is fine. We do not impose foreign diets on Indian patients." },
      { q: "What about fruit? People say diabetics cannot eat fruit.", a: "Whole fruits in measured portions are fine and beneficial. Whole fruit comes with fibre that slows glucose absorption. Fruit juice (even fresh) is the problem — concentrated sugar without fibre. We typically include 1-2 whole fruits daily in the plan." },
      { q: "I am on insulin — can diet still help?", a: "Yes, substantially. Diet helps reduce insulin requirements, improve glucose stability, prevent hypoglycaemic episodes, and reduce long-term complications. Many insulin-dependent clients see their insulin doses halve over 6 months of disciplined eating." },
      { q: "What if my doctor disagrees with reducing medication?", a: "We never advise stopping or reducing medication unilaterally. Any change to your medication regimen happens through your physician based on improved lab values. We provide them with the dietary intervention details and the lab data; they decide on medication adjustments." },
    ],
    related: ["pcod-pcos", "heart-disease", "lipid-profile-cholesterol"],
  },

  "pcod-pcos": {
    slug: "pcod-pcos",
    phpPath: "/treatment/pcod-pcos.php",
    title: "PCOD / PCOS",
    h1: "PCOS / PCOD Diet Plan in Gurgaon",
    metaTitle: "Best PCOS / PCOD Diet Plan in Gurgaon | Dietitian Priyatama | Go Moringa",
    metaDescription: "PCOS / PCOD diet plan by Go Moringa — hormone-context-sensitive Indian eating for weight loss, cycle regulation, fertility. 20 years experience.",
    heroImage: "/assets/treatment/pcos.jpg",
    introLead: "PCOS / PCOD affects roughly 1 in 5 Indian women of reproductive age — and in Gurgaon's young female population, we see this every single week. Dietary intervention is the most evidence-backed first-line treatment.",
    aboutCondition: "Polycystic Ovary Syndrome (PCOS) and Polycystic Ovarian Disease (PCOD) are hormone-related conditions causing irregular periods, weight gain (especially abdominal), acne, hair fall, excess facial/body hair, mood swings, and difficulty conceiving. The underlying mechanism involves insulin resistance, elevated androgens, and chronic low-grade inflammation. PCOS often runs alongside hypothyroidism, vitamin D deficiency, and a tendency toward Type 2 diabetes — making dietary intervention even more impactful. Symptoms typically appear in late teens or early 20s, but diagnosis often comes much later.",
    howDietHelps: "PCOS diet works on three fronts: (1) reducing insulin resistance through low-glycaemic carbohydrate choices, regular meal timing, and weight loss; (2) lowering chronic inflammation through anti-inflammatory foods and elimination of common inflammatory triggers; (3) supporting hormonal balance through adequate protein, healthy fats (essential for hormone production), and micronutrients like inositol-rich foods, zinc, magnesium, and vitamin D. Most PCOS clients see cycle regulation within 3-6 months and visible improvements in skin, hair, and energy within 2-3 months.",
    foodsToInclude: [
      "Low-glycaemic carbs: bajra, jowar, ragi, oats, brown rice (portion-controlled)",
      "Leafy greens (palak, methi, sarson — daily)",
      "Lentils, chickpeas, kidney beans (high fibre + protein)",
      "Berries, jamun, guava, apple, pear (low-GI fruits)",
      "Healthy fats: nuts, seeds, avocado, ghee in moderation",
      "Omega-3 sources: walnuts, flaxseed, fatty fish",
      "Cinnamon (helps insulin sensitivity)",
      "Methi (fenugreek) seeds (helps glucose and androgens)",
      "Spearmint tea (lowers excess testosterone in some studies)",
      "Eggs (full eggs, including yolk)",
    ],
    foodsToAvoid: [
      "Refined sugar in all forms",
      "Maida-based foods: bread, naan, pizza, pasta, biscuits",
      "Sweetened beverages, packaged juice",
      "Excess dairy (in some women — try elimination test)",
      "Fried and processed foods: chips, fries, samosa, kachori",
      "White rice in large portions (especially without protein/fibre)",
      "Trans fats: vanaspati, deep-fried foods, packaged baked goods",
      "Alcohol (worsens insulin resistance + liver health)",
      "Late-night eating (disrupts circadian hormones)",
    ],
    sampleDay: [
      { meal: "Early morning", description: "Methi-jeera water OR cinnamon water on empty stomach" },
      { meal: "Breakfast (within 1 hr of waking)", description: "2 eggs (boiled/scrambled) + 1 slice multigrain toast + sautéed spinach OR vegetable poha with peanuts + boiled egg" },
      { meal: "Mid-morning", description: "1 fruit (apple/pear/orange) + 5 walnuts" },
      { meal: "Lunch", description: "2 bajra roti + 1 katori dal + 1 katori paneer/chicken/fish + leafy green sabzi + salad + curd" },
      { meal: "Tea time", description: "Spearmint tea + roasted chana (small bowl) OR mixed seeds (1 tbsp)" },
      { meal: "Dinner (by 8 PM)", description: "Vegetable soup OR 1 roti + paneer/dal + heavy sabzi + salad" },
      { meal: "Bedtime (if needed)", description: "Warm haldi milk OR chamomile tea" },
    ],
    faqs: [
      { q: "Can PCOS be cured with diet?", a: "PCOS is not 'cured' — it is a hormonal pattern that is managed lifelong. But with diet and lifestyle, symptoms can be eliminated entirely: regular cycles, no acne, no hair loss, normal weight, normal fertility. Most clients reach this symptom-free state within 6-9 months and maintain it through lifestyle." },
      { q: "How much weight will I need to lose?", a: "Even 5-10 percent body weight reduction often regularises cycles and improves fertility. Total loss varies by case. We focus on body composition (especially abdominal fat) more than just the scale number." },
      { q: "Will my periods become regular?", a: "Most clients see cycle regulation within 3-6 months of disciplined dietary adherence. About 70-80 percent reach predictable monthly cycles without hormonal medication. The remaining cases often need shorter-term hormonal support alongside diet, decided by a gynaecologist." },
      { q: "I am trying to conceive. Can diet help?", a: "Significantly. Improved insulin sensitivity, hormonal balance, and weight management all directly improve ovulation and conception chances. Many PCOS clients conceive within 6-12 months of starting our protocol, often after years of trying. We coordinate with your gynaecologist if you are already in fertility treatment." },
      { q: "What about dairy — should I cut it out?", a: "Not by default. Some PCOS clients (about 30 percent) improve significantly with reduced or eliminated dairy. We do a structured elimination test if your current pattern includes a lot of dairy and other PCOS approaches are not moving the needle." },
      { q: "Is intermittent fasting good for PCOS?", a: "Sometimes. For weight loss and insulin sensitivity, IF can help in PCOS — but it must not become excessive. Skipping meals worsens cortisol and androgens for many women. We use modified meal timing (eating window 10-12 hours) rather than strict 16:8 IF, calibrated per individual." },
    ],
    related: ["thyroid", "diabetes"],
  },

  thyroid: {
    slug: "thyroid",
    phpPath: "/treatment/thyroid.php",
    title: "Thyroid",
    h1: "Thyroid Diet Plan in Gurgaon",
    metaTitle: "Best Thyroid Diet Plan in Gurgaon | Hypothyroid and Hashimoto's | Go Moringa",
    metaDescription: "Thyroid diet plan by Go Moringa — for hypothyroidism, hyperthyroidism, Hashimoto's. Indian meal-based, medication-timing-aware. 20 years experience.",
    heroImage: "/assets/treatment/thyroid.png",
    introLead: "Thyroid disorders are increasingly common in Indian women — and the right diet, combined with proper medication timing, dramatically improves how patients feel day-to-day. Our thyroid protocol focuses on the inflammation that drives most hypothyroid cases, the nutrients the thyroid needs (iodine, selenium, zinc, vitamin D, B12), and the food-medication timing that determines how well levothyroxine actually works.",
    aboutCondition: "The thyroid is a butterfly-shaped gland in the neck that regulates metabolism, energy, body temperature, weight, and mood. Hypothyroidism (underactive) is the most common form in India — symptoms include fatigue, weight gain (especially despite normal eating), cold intolerance, hair fall, dry skin, constipation, brain fog, and irregular periods. Hashimoto's thyroiditis is the autoimmune form of hypothyroidism. Hyperthyroidism (overactive) is less common but causes weight loss, palpitations, anxiety, heat intolerance, and tremors. Subclinical thyroid issues (borderline TSH) are extremely common and benefit substantially from dietary intervention.",
    howDietHelps: "Thyroid diet works through: (1) reducing inflammation that underlies autoimmune thyroiditis, (2) providing the micronutrients the thyroid needs (iodine, selenium, zinc, tyrosine, iron), (3) supporting gut health since 20 percent of thyroid hormone is converted in the gut, (4) timing meals around medication so levothyroxine is absorbed properly (this is often the biggest single fix), and (5) supporting weight loss against the metabolic slowdown hypothyroid patients experience. Most clients see noticeable energy improvement within 4-6 weeks; TSH normalisation typically follows by 3 months.",
    foodsToInclude: [
      "Iodised salt (in moderation)",
      "Brazil nuts (1-2 daily — selenium powerhouse)",
      "Eggs (especially the yolk — iodine + selenium)",
      "Fish (twice weekly — iodine + omega-3)",
      "Yoghurt and curd (gut health)",
      "Leafy greens cooked, not raw in excess (palak, methi)",
      "Zinc-rich foods: pumpkin seeds, cashews, chickpeas",
      "Iron-rich foods: jaggery, dates, ragi, sesame seeds",
      "Vitamin D-rich foods and sunlight exposure",
      "Whole grains: ragi, bajra, jowar, quinoa",
    ],
    foodsToAvoid: [
      "Raw cruciferous vegetables in excess (cabbage, cauliflower, broccoli, kale — fine cooked, problematic raw in large quantity)",
      "Excess soy in unfermented forms",
      "Highly processed foods, refined sugar (worsens inflammation)",
      "Gluten — for Hashimoto's specifically (controversial; we test per case)",
      "Fluoride-rich water in excess (impacts iodine uptake)",
      "Coffee/tea within 1 hour of thyroid medication",
      "Calcium supplements within 4 hours of thyroid medication",
      "Iron supplements within 4 hours of thyroid medication",
      "Late-night eating (worsens hormonal regulation)",
    ],
    sampleDay: [
      { meal: "On waking", description: "Thyroid medication (levothyroxine) with plain water, on empty stomach. Wait 30-60 min before anything else." },
      { meal: "Breakfast (after 60 min)", description: "Vegetable poha with peanuts + 1 boiled egg + green tea (not within 1 hr of meds)" },
      { meal: "Mid-morning", description: "1 fruit + 1-2 Brazil nuts" },
      { meal: "Lunch", description: "2 ragi/bajra roti + dal + paneer/chicken + cooked sabzi (avoid raw cruciferous) + curd" },
      { meal: "Tea time", description: "Green tea + roasted chana / makhana" },
      { meal: "Dinner (by 7:30 PM)", description: "Vegetable soup + 1 roti + fish/dal + sabzi" },
      { meal: "Bedtime", description: "Warm haldi milk (if not taking medication that conflicts)" },
    ],
    faqs: [
      { q: "Can diet replace my thyroid medication?", a: "Usually not, especially for full hypothyroidism or autoimmune Hashimoto's. Diet supports the thyroid and dramatically improves how you feel, but levothyroxine replacement is typically needed long-term. For subclinical / borderline cases, diet alone often brings TSH back into normal range." },
      { q: "Why does my doctor say timing of thyroid medication matters?", a: "Levothyroxine is poorly absorbed if you eat, drink coffee, or take other supplements (especially calcium or iron) within 30-60 minutes of taking it. Most thyroid patients we see were getting suboptimal results because of meal timing. Fixing this alone often improves TSH significantly without changing dose." },
      { q: "Should I cut out gluten for Hashimoto's?", a: "Possibly. Some Hashimoto's patients improve substantially with gluten elimination; others do not. We do a structured 6-8 week elimination trial with antibody re-testing rather than recommending it blindly to everyone." },
      { q: "Will I lose the thyroid weight?", a: "Yes — with the right protocol. Hypothyroid weight is harder than non-thyroid weight, but absolutely achievable. We use a slightly lower-calorie plan with adequate protein, optimised micronutrients, and patience — typically 1-2 kg/month vs 2-4 kg for non-thyroid clients." },
      { q: "What if I have both thyroid and PCOS?", a: "Very common combination — both have inflammation and insulin resistance components. We coordinate both diet plans into one, addressing both conditions simultaneously. Many of our female clients have this dual diagnosis." },
    ],
    related: ["pcod-pcos", "diabetes"],
  },

  "high-blood-pressure": {
    slug: "high-blood-pressure",
    phpPath: "/treatment/high-blood-pressure.php",
    title: "Hypertension",
    h1: "Hypertension (High Blood Pressure) Diet in Gurgaon",
    metaTitle: "Best Hypertension Diet Plan in Gurgaon | DASH-Style Indian Diet | Go Moringa",
    metaDescription: "High blood pressure diet plan by Go Moringa — DASH-style Indian eating, sodium-managed, potassium-rich. Most clients see systolic drop 10-15 mmHg in 8 weeks.",
    heroImage: "/assets/treatment/High BP.jpg",
    introLead: "High blood pressure is responsive to dietary intervention faster than almost any other chronic condition. Most clients see systolic blood pressure drop by 10-15 mmHg within 8 weeks of disciplined adherence to our protocol.",
    aboutCondition: "Hypertension (BP consistently above 130/80) is the leading cause of stroke and heart attack in India. It is typically silent — most patients have no symptoms until damage has occurred. Risk factors include excess sodium, low potassium, abdominal obesity, chronic stress, sleep deprivation, alcohol, and a family history. Pre-hypertension (120-129 systolic) is reversible through diet alone in nearly all cases. Stage 1 and 2 hypertension often respond significantly to diet, reducing medication needs.",
    howDietHelps: "The DASH diet (Dietary Approaches to Stop Hypertension) is the most evidence-backed dietary intervention for BP. We translate DASH into Indian meal patterns: emphasis on potassium-rich foods (which counteract sodium), reduced sodium intake (target under 2,300 mg/day), adequate magnesium and calcium, and low-glycaemic carbohydrates for weight management. The combination typically reduces BP within 4-8 weeks.",
    foodsToInclude: [
      "Potassium-rich: banana, coconut water, papaya, orange, sweet potato",
      "Leafy greens (palak, methi — daily)",
      "Beetroot (specifically — drops BP 4-10 mmHg in studies)",
      "Lentils and beans (magnesium + fibre)",
      "Yoghurt and milk (calcium — protective for BP)",
      "Whole grains: oats, ragi, bajra",
      "Garlic (raw or lightly cooked, daily)",
      "Berries, pomegranate (antioxidants)",
      "Fatty fish (twice weekly — omega-3)",
      "Nuts: walnuts, almonds (magnesium)",
    ],
    foodsToAvoid: [
      "Excess table salt and salty Indian condiments (papad, achaar, etc.)",
      "Packaged foods: namkeen, chips, instant noodles, sauces (sodium bombs)",
      "Processed meats",
      "Restaurant food in excess (very high hidden sodium)",
      "Sweetened beverages",
      "Excess caffeine (causes BP spikes)",
      "Alcohol",
      "Tobacco in any form",
      "Trans fats: vanaspati, deep-fried, packaged baked goods",
    ],
    sampleDay: [
      { meal: "Early morning", description: "Beetroot juice (small glass) OR coconut water + 5 soaked almonds" },
      { meal: "Breakfast", description: "Oats porridge with milk + banana + crushed walnuts + cinnamon" },
      { meal: "Mid-morning", description: "1 orange OR 1 cup papaya" },
      { meal: "Lunch", description: "2 phulka + dal + paneer/chicken + leafy green sabzi + salad + low-salt curd" },
      { meal: "Tea time", description: "Green tea + 1 fruit OR roasted chana" },
      { meal: "Dinner (by 7:30 PM)", description: "Mixed vegetable soup + 1 roti + dal + sabzi + small salad" },
      { meal: "Bedtime", description: "1 cup warm milk with haldi (calcium + magnesium)" },
    ],
    faqs: [
      { q: "How fast will my BP come down?", a: "Most disciplined clients see 5-10 mmHg drop within 2-3 weeks, and 10-15 mmHg by 8 weeks. Significant for early-stage; combined with medication for advanced cases." },
      { q: "Can I come off BP medication with diet?", a: "Many early-stage hypertensive clients have, under their physician's supervision. We do not recommend changing medication unilaterally. We provide your physician with documented BP improvements and they decide on medication adjustments." },
      { q: "How much salt can I have?", a: "Target is under 2,300 mg sodium daily (about 1 tsp salt total across the day, factoring in salt in cooked foods). Most Indians consume 8-10g — 4-5 times over target. The bigger reduction comes from cutting packaged foods, papad, achaar, and restaurant eating." },
      { q: "Is coconut water really good for BP?", a: "Yes — high in potassium, low in sodium, naturally hydrating. One small glass daily is helpful. Not a replacement for medication, but a meaningful adjunct." },
      { q: "What if I am also overweight?", a: "Weight loss is one of the single biggest BP-lowering interventions. Every 10 kg of weight loss in an overweight hypertensive typically reduces systolic BP by 5-20 mmHg. Our plans combine BP management with weight loss." },
    ],
    related: ["heart-disease", "diabetes", "lipid-profile-cholesterol"],
  },

  "heart-disease": {
    slug: "heart-disease",
    phpPath: "/treatment/heart-disease.php",
    title: "Heart Disease",
    h1: "Heart-Healthy Diet Plan in Gurgaon",
    metaTitle: "Cardiac Diet Plan in Gurgaon | Post-MI / Post-Bypass Dietitian | Go Moringa",
    metaDescription: "Heart disease diet plan by Go Moringa — cardiac diet, post-bypass, post-MI nutrition. Designed alongside cardiologists across NCR. 20 years experience.",
    heroImage: "/assets/treatment/heart disease.jpg",
    introLead: "Cardiac diets need to be precise — wrong choices can strain a recovering heart, while right choices significantly reduce future event risk. We have worked alongside cardiology teams across Gurgaon hospitals for two decades on diets for hypertension, coronary artery disease, post-angioplasty, post-bypass, and heart-failure patients.",
    aboutCondition: "Heart disease encompasses coronary artery disease (blockages from plaque buildup), heart failure (weakened pumping), arrhythmias, and post-event recovery (post-MI, post-bypass, post-angioplasty). India has one of the world's highest rates of coronary disease, with events occurring 10-15 years earlier than in Western populations. Major drivers: high LDL cholesterol, hypertension, diabetes, abdominal obesity, smoking, chronic stress, and family history.",
    howDietHelps: "Cardiac diet works on multiple fronts: lowering LDL cholesterol (the main plaque-builder), raising HDL (protective), reducing triglycerides, controlling blood pressure, managing weight, reducing inflammation, and supporting blood vessel health. The Mediterranean-DASH hybrid is the most evidence-backed pattern, which we adapt to Indian meal habits.",
    foodsToInclude: [
      "Oats (specifically — beta-glucan lowers LDL)",
      "Fatty fish (twice weekly — omega-3 for cardiac health)",
      "Walnuts, almonds, pistachios (heart-healthy fats)",
      "Olive oil + mustard oil (preferred cooking oils)",
      "Leafy greens (daily)",
      "Berries, pomegranate, apple",
      "Whole grains: ragi, bajra, jowar",
      "Lentils, beans, chickpeas (high fibre)",
      "Garlic (raw — lowers LDL slightly)",
      "Avocado, flaxseeds, chia seeds",
    ],
    foodsToAvoid: [
      "Trans fats: vanaspati, deep-fried, packaged baked goods",
      "Excess saturated fat: butter, ghee in large amounts, red meat",
      "Refined carbs: maida, white rice in excess, sugar",
      "Salt and high-sodium foods (papad, achaar, namkeen, packaged)",
      "Sweetened beverages, packaged juice",
      "Tobacco and alcohol (especially for recent events)",
      "Restaurant meals (high in salt + hidden trans fats)",
    ],
    sampleDay: [
      { meal: "Early morning", description: "Cinnamon water + soaked walnuts (5) + 1 almond" },
      { meal: "Breakfast", description: "Oats with low-fat milk + berries + crushed flaxseeds + 1 boiled egg white (or whole egg, per cardiologist)" },
      { meal: "Mid-morning", description: "1 fruit (apple/orange/pomegranate)" },
      { meal: "Lunch", description: "2 ragi/bajra roti + dal + leafy green sabzi + salad with olive oil + small portion curd" },
      { meal: "Tea time", description: "Green tea + roasted chana (small bowl)" },
      { meal: "Dinner (by 7:30 PM)", description: "Vegetable soup + 1 roti + grilled fish/dal + steamed vegetables + salad" },
      { meal: "Bedtime", description: "1 cup low-fat milk with haldi" },
    ],
    faqs: [
      { q: "How long until my lipid profile improves?", a: "LDL responds within 6-8 weeks of consistent dietary change. Significant LDL reductions of 15-30 percent are achievable in many clients. Triglycerides respond even faster — often within 4 weeks." },
      { q: "What if I have just had bypass or angioplasty?", a: "Post-procedure diets need to be especially careful for the first 6-8 weeks — easy-to-digest, low-salt, controlled-portion. We coordinate with the cardiology team on specifics. After initial recovery, we transition to long-term cardiac-protective eating." },
      { q: "Can diet reverse plaque buildup?", a: "Some plaque regression has been documented in disciplined long-term cardiac diet adherence. For most clients, the realistic goal is preventing progression and reducing event risk — both of which diet achieves substantially." },
      { q: "What about ghee — Indian families consider it healthy?", a: "Ghee in small amounts (1-2 teaspoons daily) is fine for most cardiac clients. Excess ghee, butter, or any saturated fat raises LDL. We do not ban ghee; we measure it." },
      { q: "I am on statins. Does diet still matter?", a: "Yes, even more so. Statins lower LDL but do not address inflammation, oxidation, or blood vessel health to the same extent diet does. Many cardiologists target a lower statin dose once dietary adherence is established." },
    ],
    related: ["high-blood-pressure", "lipid-profile-cholesterol", "diabetes"],
  },

  "lipid-profile-cholesterol": {
    slug: "lipid-profile-cholesterol",
    phpPath: "/treatment/lipid-profile-cholesterol.php",
    title: "Lipid Profile / Cholesterol",
    h1: "Lipid Profile / Cholesterol Management Diet in Gurgaon",
    metaTitle: "Cholesterol Lowering Diet Plan in Gurgaon | LDL HDL Management | Go Moringa",
    metaDescription: "Cholesterol management diet by Go Moringa — lower LDL, raise HDL, reduce triglycerides through Indian meal-based eating.",
    heroImage: "/assets/treatment/LP-cholestrol.jpg",
    introLead: "Abnormal lipid profile — high LDL, low HDL, high triglycerides — is one of the strongest risk factors for heart attack and stroke. Our cholesterol-management protocol typically reduces LDL by 15-30 percent within 8 weeks of disciplined adherence.",
    aboutCondition: "Lipid profile measures four key markers: Total cholesterol, LDL (the 'bad' one that builds plaque), HDL (the 'good' one that clears plaque), and triglycerides. Most Indian adults over 35 have at least one abnormal marker. Genetic factors, sedentary lifestyle, refined-carb-heavy diets, abdominal obesity, and chronic stress all worsen lipid profiles.",
    howDietHelps: "Dietary changes affect lipids through: (1) reducing saturated and trans fats (lowers LDL), (2) increasing soluble fibre — especially from oats, beans, fruits — which binds cholesterol in the gut, (3) increasing omega-3 fats (lowers triglycerides, raises HDL), (4) reducing refined carbs (lowers triglycerides), (5) weight loss (improves all four markers), and (6) plant sterols/stanols from nuts, seeds, and certain plants.",
    foodsToInclude: [
      "Oats and oat-based foods (beta-glucan)",
      "Soluble fibre: apples, pears, oranges, beans, lentils, eggplant, ladyfinger",
      "Walnuts, almonds, pistachios (small handful daily)",
      "Flaxseeds, chia seeds (omega-3 + fibre)",
      "Fatty fish (twice weekly)",
      "Olive oil, mustard oil (preferred over palm/refined)",
      "Garlic (modest LDL reduction)",
      "Soy products in moderate quantity (some evidence for LDL reduction)",
      "Green tea (2-3 cups daily)",
      "Leafy greens (folate + fibre)",
    ],
    foodsToAvoid: [
      "Trans fats: vanaspati, deep-fried, packaged baked goods, biscuits",
      "Excess saturated fat: butter in excess, ghee in excess, red meat, cream",
      "Refined carbs: maida, white rice in large portions, sugar",
      "Sweetened beverages (raise triglycerides dramatically)",
      "Coconut oil in excess",
      "Alcohol (raises triglycerides)",
      "Restaurant deep-fried foods, fried snacks",
    ],
    sampleDay: [
      { meal: "Early morning", description: "Garlic-water (1 small clove crushed in warm water, on empty stomach)" },
      { meal: "Breakfast", description: "Oats with low-fat milk + flaxseed + berries + 5 walnuts" },
      { meal: "Mid-morning", description: "1 apple or pear (with skin)" },
      { meal: "Lunch", description: "2 ragi roti + dal + beans/chickpea sabzi + salad with olive oil + small curd" },
      { meal: "Tea time", description: "Green tea + roasted chana (small bowl)" },
      { meal: "Dinner (by 7:30 PM)", description: "Vegetable soup + 1 roti + fish/dal + steamed vegetables" },
      { meal: "Bedtime", description: "Low-fat milk with haldi OR chamomile tea" },
    ],
    faqs: [
      { q: "How much can diet lower my LDL?", a: "15-30 percent reduction is realistic for most disciplined clients within 8 weeks. Some clients with very high baseline LDL see even larger drops. This often eliminates the need for high-dose statins." },
      { q: "My HDL is low. How do I raise it?", a: "HDL is harder to raise than LDL is to lower. The best HDL-raisers are physical activity (especially aerobic), omega-3 fats from fish and walnuts, weight loss, and reducing refined carbs. Diet alone may raise HDL 5-10 percent; combined with exercise can do more." },
      { q: "Why are my triglycerides so high?", a: "Triglycerides usually rise from excess sugar, refined carbs, and alcohol — not from dietary fat as commonly thought. Cutting sweetened beverages, mithai, refined-flour foods, and alcohol often drops triglycerides 30-40 percent within 4-6 weeks." },
      { q: "Are eggs bad for cholesterol?", a: "Long-running myth — for most people, dietary cholesterol from eggs does not significantly raise blood cholesterol. 1 whole egg daily is fine for most clients." },
      { q: "Can I have ghee?", a: "Yes, in measured amounts (1-2 teaspoons daily total). Ghee is mostly saturated fat — small amounts are fine, large amounts raise LDL. We measure rather than ban." },
    ],
    related: ["heart-disease", "high-blood-pressure", "diabetes"],
  },

  "uric-acid": {
    slug: "uric-acid",
    phpPath: "/treatment/uric-acid.php",
    title: "Gout / Uric Acid",
    h1: "Gout / Uric Acid Diet Plan in Gurgaon",
    metaTitle: "Best Uric Acid / Gout Diet Plan in Gurgaon | Go Moringa",
    metaDescription: "Uric acid and gout diet plan by Go Moringa — low-purine Indian meals, anti-inflammatory protocol. Most clients see uric acid normalise in 8-12 weeks.",
    heroImage: "/assets/treatment/Uric Acid.jpg",
    introLead: "High uric acid leads to gout — extremely painful joint inflammation, typically starting in the big toe. Dietary management is highly effective: most clients see uric acid normalise within 8-12 weeks of disciplined adherence, with significant reduction in gout attacks.",
    aboutCondition: "Uric acid is a waste product from purine breakdown. When kidneys cannot clear it fast enough, it crystallises in joints (causing gout), forms kidney stones, or both. Normal levels: under 6 mg/dL for women, under 7 for men. Risk factors: red meat, organ meats, certain fish, alcohol (especially beer), fructose-sweetened drinks, dehydration, obesity, and genetic predisposition.",
    howDietHelps: "Diet works by: (1) reducing purine intake (the source of uric acid), (2) improving uric acid excretion through hydration, (3) reducing fructose which raises uric acid, (4) addressing weight (lowers uric acid 1-2 mg/dL with even 5-10 percent weight loss), and (5) anti-inflammatory eating during active gout attacks.",
    foodsToInclude: [
      "Plenty of water (3-4 litres daily)",
      "Cherry, berries (specifically lower uric acid)",
      "Vitamin C-rich foods: orange, amla, guava",
      "Coffee in moderation (lowers uric acid slightly)",
      "Low-fat dairy (specifically protective)",
      "Whole grains: ragi, jowar, bajra",
      "Vegetables (most are fine — even spinach in moderation)",
      "Eggs (low purine)",
      "Lentils in moderate quantity",
    ],
    foodsToAvoid: [
      "Organ meats: liver, kidney, brain (highest purines)",
      "Red meat (beef, lamb, pork — high purine)",
      "Certain fish: sardines, anchovies, mackerel, tuna",
      "Alcohol (especially beer — major trigger)",
      "Sweetened beverages, fruit juice (fructose raises uric acid)",
      "Mushrooms, asparagus, cauliflower in excess (moderate purine)",
      "Yeast-based foods in excess",
    ],
    faqs: [
      { q: "What should I eat during a gout attack?", a: "Plenty of water, cherries (specifically helpful), low-fat dairy, vegetables, complex carbs. Avoid alcohol, organ meats, sweetened drinks. Ice + rest + your prescribed medication for the attack itself." },
      { q: "Will I have to give up non-veg entirely?", a: "Not necessarily. Red meat, organ meats, and certain fish need to go. Chicken in moderate amounts is usually fine. Eggs and dairy are protective." },
      { q: "Can I drink alcohol at all?", a: "Beer is the worst — high purine + dehydrating + raises uric acid through multiple mechanisms. Spirits and wine in small amounts are tolerated by some clients, but during active disease management, complete abstinence is safest." },
      { q: "How much water should I drink?", a: "Target 3-4 litres daily — flushes uric acid through kidneys. Most gout clients we see are chronically under-hydrated." },
    ],
    related: ["heart-disease", "diabetes", "metabolic-syndrome"],
  },

  osteoporosis: {
    slug: "osteoporosis",
    phpPath: "/treatment/osteoporosis.php",
    title: "Osteoporosis",
    h1: "Osteoporosis Diet and Bone Health in Gurgaon",
    metaTitle: "Best Osteoporosis Diet Plan in Gurgaon | Bone Health Dietitian | Go Moringa",
    metaDescription: "Osteoporosis diet plan by Go Moringa — calcium, vitamin D, protein, magnesium for bone density. Indian meals, post-menopausal protocols.",
    heroImage: "/assets/treatment/osteoprosis.jpg",
    introLead: "Osteoporosis affects roughly 1 in 3 post-menopausal Indian women — far higher than commonly recognised. Dietary intervention combined with appropriate medication slows or reverses bone density loss. Pre-osteoporotic osteopenia is often fully reversible with diet, weight-bearing exercise, and adequate vitamin D.",
    aboutCondition: "Osteoporosis is reduced bone density and strength, leading to fragile bones that fracture easily. Symptoms are absent until a fracture occurs — typically in the wrist, hip, or spine. Indian women are at especially high risk due to low calcium intake, low vitamin D levels (despite the sun), early menopause, small body frames, and inadequate protein. Men get osteoporosis too, especially after 65.",
    howDietHelps: "Bone health diet provides: (1) adequate calcium (1000-1200 mg daily for most adults), (2) adequate vitamin D (sunlight + diet + supplementation when deficient), (3) adequate protein (essential — low protein worsens bone loss), (4) magnesium, vitamin K2, zinc, boron, and (5) reducing factors that accelerate bone loss — excess salt, caffeine, alcohol, refined sugar.",
    foodsToInclude: [
      "Dairy: milk, curd, paneer, cheese (calcium powerhouse)",
      "Ragi (highest calcium among Indian grains)",
      "Sesame seeds, til (very high calcium)",
      "Green leafy vegetables (spinach, methi, sarson)",
      "Almonds, walnuts (calcium + magnesium)",
      "Eggs (vitamin D + protein)",
      "Fatty fish (twice weekly — vitamin D)",
      "Adequate protein from dal, paneer, eggs, chicken (1-1.2 g/kg body weight)",
      "Fermented foods (vitamin K2)",
    ],
    foodsToAvoid: [
      "Excess salt (causes calcium loss in urine)",
      "Excess caffeine (more than 3 cups/day)",
      "Carbonated cola drinks (phosphoric acid leaches calcium)",
      "Excess alcohol (impairs bone formation)",
      "Refined sugar in excess (worsens bone health)",
      "Crash diets (low protein = bone loss)",
    ],
    faqs: [
      { q: "How much calcium do I need daily?", a: "1,000-1,200 mg for most adults; 1,200 mg for post-menopausal women. Most Indian diets provide only 400-600 mg — significant gap. We close it through milk, curd, paneer, ragi, sesame, and supplementation where needed." },
      { q: "Why are Indians so deficient in vitamin D despite the sunlight?", a: "Indoor lifestyle, full-body clothing, sunscreen, skin pigmentation reducing vitamin D synthesis, and inadequate dietary sources. Most Indian adults benefit from vitamin D testing and supplementation." },
      { q: "Should I take calcium supplements?", a: "Only if dietary intake genuinely cannot meet needs. Whole-food calcium is better absorbed and does not carry the cardiovascular concerns some calcium supplements have raised." },
      { q: "Does exercise affect bone?", a: "Critically. Weight-bearing exercise — walking, jogging, resistance training — is as important as diet for bone density. Sedentary clients lose bone fast despite good diet." },
    ],
    related: ["osteoarthritis", "micronutrient-deficiency"],
  },

  osteoarthritis: {
    slug: "osteoarthritis",
    phpPath: "/treatment/osteoarthritis.php",
    title: "Osteoarthritis",
    h1: "Osteoarthritis Diet and Joint Health in Gurgaon",
    metaTitle: "Best Osteoarthritis / Joint Pain Diet Plan in Gurgaon | Go Moringa",
    metaDescription: "Osteoarthritis diet plan by Go Moringa — anti-inflammatory Indian eating for knee, hip, joint pain. Weight management to reduce joint load. 20 years experience.",
    heroImage: "/assets/treatment/osteoarthritis-treatment.jpg",
    introLead: "Osteoarthritis pain — especially in knees and hips — responds significantly to anti-inflammatory dietary intervention combined with weight management. Many of our clients report noticeable pain reduction within 6-8 weeks of disciplined eating, even before significant weight loss.",
    aboutCondition: "Osteoarthritis is wear-and-tear arthritis — cartilage breakdown causing pain, stiffness, and reduced movement. Most common in knees, hips, hands, and spine. Risk factors: ageing, obesity (knee OA is dramatically worse with excess weight), previous joint injury, repetitive stress, and genetic predisposition. Weight is the single biggest modifiable factor — every kg of weight reduction reduces knee load by approximately 4 kg during walking.",
    howDietHelps: "Anti-inflammatory dietary patterns reduce joint pain and slow cartilage breakdown. Weight loss reduces mechanical joint stress. Specific nutrients support cartilage and collagen synthesis. Avoiding inflammatory triggers — refined sugar, refined carbs, excess omega-6 oils — often reduces pain even before measurable weight loss.",
    foodsToInclude: [
      "Fatty fish (twice weekly — omega-3 anti-inflammatory)",
      "Walnuts, flaxseed, chia seeds (omega-3)",
      "Turmeric (curcumin — well-studied joint benefits)",
      "Ginger (anti-inflammatory)",
      "Berries, pomegranate, cherries",
      "Leafy greens (vitamin K + antioxidants)",
      "Bone broth (collagen support)",
      "Adequate protein (cartilage repair)",
      "Vitamin C-rich foods (collagen synthesis)",
    ],
    foodsToAvoid: [
      "Refined sugar (pro-inflammatory)",
      "Refined carbs: maida, white rice in excess",
      "Trans fats: vanaspati, deep-fried foods",
      "Excessive omega-6 oils: refined sunflower, safflower, soybean oil in excess",
      "Processed meats (sausages, salami)",
      "Excess alcohol",
    ],
    faqs: [
      { q: "How much does losing weight help knee pain?", a: "Dramatically. Each kg of weight loss reduces knee load by approximately 4 kg during walking. Most overweight OA clients see significant pain reduction with even 5-10 kg of weight loss." },
      { q: "Does turmeric actually work?", a: "Curcumin (the active in turmeric) has reasonable clinical evidence for OA pain reduction — comparable to NSAIDs in some studies. Indian cooking provides modest amounts; therapeutic doses often need supplementation. Use with black pepper for absorption." },
      { q: "Should I take collagen supplements?", a: "Modest evidence for joint benefit in some studies. We typically do not recommend by default — bone broth, adequate protein, and vitamin C from food provide collagen synthesis support more cost-effectively." },
      { q: "Can I still exercise with osteoarthritis?", a: "Yes — appropriate movement protects cartilage. Low-impact activities (swimming, cycling, walking on flat) are ideal. We coordinate with your physiotherapist on specifics." },
    ],
    related: ["osteoporosis", "micronutrient-deficiency"],
  },

  depression: {
    slug: "depression",
    phpPath: "/treatment/depression.php",
    title: "Depression and Anxiety",
    h1: "Depression and Anxiety Diet Support in Gurgaon",
    metaTitle: "Diet for Depression and Anxiety in Gurgaon | Nutritional Psychiatry | Go Moringa",
    metaDescription: "Diet support for depression and anxiety by Go Moringa — gut-brain axis, omega-3, B vitamins, blood sugar stability. Adjunct to psychiatric care.",
    heroImage: "/assets/services/diet-for-depression.jpg",
    introLead: "The relationship between gut, food, and mental health is one of the most actively researched areas in psychiatry. Diet is not a replacement for psychiatric care — but as an adjunct to therapy and medication, it makes a measurable difference for depression and anxiety.",
    aboutCondition: "Depression and anxiety are complex conditions with biological, psychological, and social drivers. Dietary intervention works as an adjunct — not a primary treatment — to therapy and (when needed) medication. The gut-brain axis, blood sugar stability, omega-3 status, B vitamins (especially B12 and folate), and vitamin D all influence mood regulation.",
    howDietHelps: "Dietary mechanisms in mood: (1) gut microbiome health influences neurotransmitter production (most serotonin is made in the gut), (2) blood sugar stability prevents the mood swings of glucose dips, (3) omega-3 fats are direct neuroinflammation modulators, (4) B vitamins (especially B12) deficiency causes depressive symptoms, (5) iron deficiency contributes to fatigue often misattributed to depression, (6) elimination of pro-inflammatory foods reduces neuroinflammation.",
    foodsToInclude: [
      "Fatty fish (twice weekly — omega-3)",
      "Walnuts, flaxseeds, chia (omega-3)",
      "Eggs (B12, choline)",
      "Leafy greens (folate)",
      "Whole grains (steady glucose)",
      "Fermented foods: curd, kimchi, kefir (gut health)",
      "Dark chocolate in moderation",
      "Berries, citrus (antioxidants + vitamin C)",
      "Lentils, beans (folate + fibre)",
      "Plenty of water (dehydration worsens mood)",
    ],
    foodsToAvoid: [
      "Refined sugar (mood crashes after spikes)",
      "Processed foods (pro-inflammatory + nutrient-poor)",
      "Excess caffeine (worsens anxiety)",
      "Alcohol (depressant + disrupts sleep)",
      "Skipping meals (blood sugar swings)",
      "Excessive ultra-processed snacks",
    ],
    faqs: [
      { q: "Can diet replace antidepressants?", a: "No — diet is an adjunct, not a replacement. If you are on antidepressants, continue them under your psychiatrist's guidance. Diet works alongside the medication and therapy, often improving response and possibly reducing dosage needs over time." },
      { q: "What if I do not feel like eating?", a: "Loss of appetite is a common depression symptom. We design plans with small, easy meals — smoothies, soups, simple toast-with-eggs — that do not require significant energy to prepare." },
      { q: "Does cutting sugar really help mood?", a: "Yes — meaningfully. The blood sugar swings from refined sugar create mood swings; consistent eating without sugar spikes creates more stable mood. Most clients notice mood stability improvement within 2-3 weeks of sugar reduction." },
      { q: "Should I take supplements?", a: "Often beneficial. Vitamin D, B12, omega-3 are commonly low in depressed patients. We test (or recommend you test) and supplement based on values rather than recommending blindly." },
    ],
    related: ["pcod-pcos", "thyroid"],
  },

  constipation: {
    slug: "constipation",
    phpPath: "/treatment/constipation.php",
    title: "Constipation",
    h1: "Constipation and Digestive Health Diet in Gurgaon",
    metaTitle: "Best Diet for Constipation in Gurgaon | Gut Health Dietitian | Go Moringa",
    metaDescription: "Constipation and gut health diet plan by Go Moringa — fibre, hydration, fermented foods. Resolve chronic constipation through diet, not laxatives.",
    heroImage: "/assets/treatment/constipation.jpg",
    introLead: "Chronic constipation is one of the most common complaints we see, and one of the easiest to fix through diet. Most clients see daily, comfortable bowel movements within 2-3 weeks of adjusted eating — without dependence on laxatives.",
    aboutCondition: "Chronic constipation — fewer than 3 bowel movements per week, hard stools, straining, incomplete evacuation — affects a significant portion of urban Indian adults. Causes include inadequate fibre, inadequate water, sedentary lifestyle, irregular meal timing, certain medications, hypothyroidism, and gut microbiome disruption.",
    howDietHelps: "Dietary fix involves: (1) gradually increasing fibre to 25-35g daily, (2) ensuring adequate hydration (fibre without water makes constipation worse), (3) supporting gut microbiome through fermented foods and prebiotic foods, (4) regular meal timing (the gut has a circadian rhythm), and (5) identifying and managing constipating triggers (excess dairy in some, low-FODMAP issues in others).",
    foodsToInclude: [
      "Soaked overnight: chia seeds, sabja, flaxseed",
      "Fruits with skin: apple, pear, guava",
      "Berries, papaya, kiwi (specifically helpful)",
      "Whole grains: oats, ragi, bajra, jowar",
      "Lentils, beans, chickpeas",
      "Leafy greens (palak, methi)",
      "Vegetables: ladyfinger, beetroot, carrot, lauki",
      "Curd, lassi (probiotic)",
      "Plenty of water (3 litres daily)",
      "Prunes (specifically very effective)",
    ],
    foodsToAvoid: [
      "Refined foods: maida, white rice in excess (low fibre)",
      "Processed snacks (low fibre, high in additives)",
      "Excess dairy in sensitive individuals",
      "Inadequate water intake",
      "Excess caffeine (dehydrating)",
      "Fried and heavy oily food",
    ],
    faqs: [
      { q: "How quickly will this work?", a: "Most clients see improvement within 3-7 days of consistent fibre + water intake. Daily comfortable bowel movements typically establish within 2-3 weeks." },
      { q: "Should I stop my laxative?", a: "Do not stop abruptly. We typically taper laxative use over 2-4 weeks as dietary changes establish regular bowel function. Do not make changes without your physician's input if you are on prescription laxatives." },
      { q: "How much water is really enough?", a: "3 litres for most adults. More if you are active or in summer. Fibre without water makes constipation worse — both need to increase together." },
      { q: "What if I have IBS?", a: "IBS-constipation pattern needs a slightly different approach — sometimes low-FODMAP elimination identifies trigger foods. We test per case rather than recommending blindly." },
    ],
    related: ["water-retention"],
  },

  "metabolic-syndrome": {
    slug: "metabolic-syndrome",
    phpPath: "/treatment/metabolic-syndrome.php",
    title: "Metabolic Syndrome",
    h1: "Metabolic Syndrome Diet Plan in Gurgaon",
    metaTitle: "Best Metabolic Syndrome Diet Plan in Gurgaon | Insulin Resistance | Go Moringa",
    metaDescription: "Metabolic syndrome diet plan by Go Moringa — addresses abdominal obesity, BP, glucose, lipids together. Indian-meal-based, 20 years experience.",
    heroImage: "/assets/treatment/metabolic yndrome.jpg",
    introLead: "Metabolic syndrome — the cluster of abdominal obesity, high BP, abnormal glucose, abnormal lipids — affects an alarming percentage of urban Indian adults. It is the strongest predictor of future heart disease and diabetes.",
    aboutCondition: "Metabolic syndrome is diagnosed when 3+ of these are present: waist circumference above 90 cm (men) or 80 cm (women), triglycerides above 150, HDL below 40 (men) or 50 (women), BP above 130/85, fasting glucose above 100. The underlying driver is insulin resistance.",
    howDietHelps: "Single coordinated approach addresses all components: low-glycaemic carbs reduce insulin resistance, fibre and lean protein support weight loss, omega-3 lowers triglycerides, potassium-rich foods lower BP, anti-inflammatory eating reduces overall risk.",
    foodsToInclude: [
      "All foods listed for diabetes diet",
      "Mediterranean staples: olive oil, fish, nuts, berries",
      "High-fibre Indian foods: oats, lentils, beans, leafy greens",
      "Cinnamon, fenugreek (insulin sensitivity)",
    ],
    foodsToAvoid: [
      "All processed and refined carbs",
      "Sweetened beverages",
      "Excess saturated fat",
      "Trans fats",
      "Restaurant food in excess",
    ],
    faqs: [
      { q: "Can metabolic syndrome be reversed?", a: "Yes, in most early-stage cases. Disciplined diet + activity + weight loss can reverse all five components for many clients. The longer it has gone unmanaged, the harder full reversal becomes, but improvement is always achievable." },
      { q: "Do I need medication if I have metabolic syndrome?", a: "Depends on severity. Many clients with mild-to-moderate metabolic syndrome avoid medication entirely with disciplined diet + lifestyle." },
    ],
    related: ["diabetes", "high-blood-pressure", "lipid-profile-cholesterol", "heart-disease"],
  },

  "abnormal-blood-fats": {
    slug: "abnormal-blood-fats",
    phpPath: "/treatment/abnormal-blood-fats.php",
    title: "Abnormal Blood Fats",
    h1: "Abnormal Blood Fats / Dyslipidemia Diet in Gurgaon",
    metaTitle: "Abnormal Blood Fats / Dyslipidemia Diet in Gurgaon | Go Moringa",
    metaDescription: "Diet plan for abnormal blood fats (dyslipidemia) by Go Moringa — comprehensive lipid management through Indian meal-based eating.",
    heroImage: "/assets/treatment/abnormal blood fats.jpg",
    introLead: "Dyslipidemia — abnormal levels of cholesterol, triglycerides, or lipoproteins — is the most diet-responsive cardiovascular risk factor. Significant improvement is achievable in 8 weeks of disciplined eating, often without high-dose medication.",
    aboutCondition: "Abnormal blood fats include high LDL, low HDL, high triglycerides, high Lp(a), and abnormal apo-B. Each carries cardiovascular risk through different mechanisms. The conventional 'cholesterol' diet covers most of these patterns simultaneously.",
    howDietHelps: "See cholesterol management — overlapping dietary strategy. Reducing saturated and trans fats, increasing soluble fibre, increasing omega-3 fats, reducing refined carbs, and weight loss together improve all lipid markers.",
    foodsToInclude: [
      "Same as cholesterol management protocol",
      "Oats, beans, lentils (soluble fibre)",
      "Walnuts, almonds, flaxseed",
      "Fatty fish",
      "Olive oil, mustard oil",
    ],
    foodsToAvoid: [
      "Trans fats, excess saturated fat",
      "Refined carbs, sugar",
      "Sweetened beverages",
      "Alcohol",
    ],
    faqs: [
      { q: "How is this different from cholesterol management?", a: "It is the same dietary approach — 'abnormal blood fats' is the broader medical term covering all lipid abnormalities." },
      { q: "Will I need lifelong medication?", a: "For genetic dyslipidemia, often yes. For lifestyle-driven dyslipidemia, dietary intervention may eliminate the need over time." },
    ],
    related: ["lipid-profile-cholesterol", "heart-disease", "metabolic-syndrome"],
  },

  gallstones: {
    slug: "gallstones",
    phpPath: "/treatment/gallstones.php",
    title: "Gallstones",
    h1: "Gallstones Diet Plan in Gurgaon",
    metaTitle: "Gallstones Diet Plan in Gurgaon | Pre and Post-Surgery Diet | Go Moringa",
    metaDescription: "Gallstones diet plan by Go Moringa — prevention, pre-surgery, post-cholecystectomy nutrition. Low-fat Indian meals, weight management.",
    heroImage: "/assets/treatment/gallstones.jpg",
    introLead: "Gallstones often go unnoticed until they cause an attack — then dietary management becomes urgent. We provide diet support before surgery (managing symptoms), after gallbladder removal (adapting to digestion changes), or for those wanting to prevent stones in the first place.",
    aboutCondition: "Gallstones form when bile becomes too concentrated — usually from rapid weight loss, very high-fat diets, or genetic factors. More common in women, especially after pregnancy. Most are asymptomatic until they obstruct the bile duct.",
    howDietHelps: "Pre-surgery: low-fat diet reduces gallbladder stimulation and attacks. Post-surgery: gradual reintroduction of fats, smaller frequent meals, fibre support. Prevention: avoiding rapid weight loss, very low-fat diets, and refined carb excess.",
    foodsToInclude: [
      "Low-fat dairy in moderation",
      "Lean protein: dal, paneer (low fat), egg whites, fish, chicken",
      "Whole grains: oats, ragi, bajra",
      "Fruits and vegetables (high fibre)",
      "Adequate water",
      "Small frequent meals (especially post-surgery)",
    ],
    foodsToAvoid: [
      "Deep-fried foods",
      "Excess ghee, butter, cream",
      "Fatty cuts of meat",
      "Heavy desserts, mithai",
      "Crash diets (causes stones)",
      "Sweetened beverages",
    ],
    faqs: [
      { q: "Can I avoid gallbladder removal with diet?", a: "Sometimes yes, for early/mild stones. We coordinate with your surgeon on the decision. Symptomatic large stones typically need surgery." },
      { q: "What changes after gallbladder removal?", a: "Bile now flows continuously into the small intestine instead of being released in concentrated bursts. Large fatty meals become harder to digest. We transition you to smaller, more frequent meals with moderate fat over 2-3 months." },
    ],
    related: ["heart-disease", "lipid-profile-cholesterol"],
  },

  "cushing-syndrome": {
    slug: "cushing-syndrome",
    phpPath: "/treatment/cushing-syndrome.php",
    title: "Cushing's Syndrome",
    h1: "Cushing's Syndrome Diet and Nutrition Support",
    metaTitle: "Cushing's Syndrome Diet Plan in Gurgaon | Steroid-Related Weight Gain | Go Moringa",
    metaDescription: "Diet support for Cushing's syndrome by Go Moringa — managing weight, blood sugar, BP, and muscle loss from cortisol excess or long-term steroid therapy.",
    heroImage: "/assets/treatment/cushing syndrome.jpg",
    introLead: "Cushing's syndrome — whether from a pituitary or adrenal tumour or from long-term steroid medication — causes weight gain, central obesity, muscle wasting, hypertension, glucose intolerance, and bone loss. Diet supports the medical treatment by managing these downstream effects.",
    aboutCondition: "Cushing's syndrome results from prolonged excess cortisol — either endogenous or exogenous (long-term high-dose steroid medication). Symptoms include central weight gain, moon face, buffalo hump, purple stretch marks, muscle weakness, easy bruising, mood changes, hypertension, diabetes, and osteoporosis.",
    howDietHelps: "Dietary support cannot reverse Cushing's — the underlying cause needs medical/surgical treatment. But diet manages the secondary problems: low-glycaemic eating to control cortisol-driven glucose elevation, adequate protein to counter muscle wasting, calcium and vitamin D to slow bone loss, low sodium to manage BP, and weight management.",
    foodsToInclude: [
      "Adequate protein at every meal (counters muscle wasting)",
      "Calcium-rich foods (bone protection)",
      "Vitamin D foods + sunlight",
      "Potassium-rich foods (banana, coconut water — counters sodium retention)",
      "Magnesium-rich foods",
      "Anti-inflammatory foods: omega-3 fish, leafy greens, berries",
    ],
    foodsToAvoid: [
      "Refined sugar (cortisol already raises glucose)",
      "Excess salt (cortisol causes sodium retention)",
      "Refined carbs",
      "Excess alcohol",
    ],
    faqs: [
      { q: "Will diet reverse my Cushing's?", a: "No — the underlying cause needs medical treatment. Diet manages the secondary effects on weight, glucose, BP, bones, and muscle." },
      { q: "I am on long-term steroids — can diet help?", a: "Yes, significantly. Many of the steroid side effects can be substantially mitigated with the right dietary approach." },
    ],
    related: ["diabetes", "osteoporosis", "high-blood-pressure"],
  },

  "micronutrient-deficiency": {
    slug: "micronutrient-deficiency",
    phpPath: "/treatment/micronutrient-deficiency.php",
    title: "Micronutrient Deficiency",
    h1: "Micronutrient Deficiency Diet and Correction",
    metaTitle: "Micronutrient Deficiency Diet Plan in Gurgaon | Iron, B12, Vit D | Go Moringa",
    metaDescription: "Micronutrient deficiency correction by Go Moringa — iron, B12, vitamin D, magnesium, zinc through Indian meal-based food-first approach.",
    heroImage: "/assets/treatment/micronutrient.jpg",
    introLead: "Micronutrient deficiencies are alarmingly common in urban Indian adults — iron, vitamin B12, vitamin D, magnesium, zinc deficiencies show up across all age groups and dietary patterns. Food-first correction is more sustainable than long-term supplementation alone.",
    aboutCondition: "Common deficiencies and their typical symptoms: iron deficiency (fatigue, hair fall, pale skin), B12 deficiency (fatigue, neurological symptoms, tingling), vitamin D (low immunity, bone pain, mood issues), magnesium (cramps, sleep issues, anxiety), zinc (skin issues, poor wound healing, frequent infections).",
    howDietHelps: "Food-based correction provides nutrients in absorbable forms with co-factors that aid absorption. Iron from food + vitamin C absorbs better than supplemental iron alone. B12 from animal foods is well-absorbed. Vitamin D from fatty fish + sunlight + diet is the most sustainable approach.",
    foodsToInclude: [
      "Iron: jaggery, dates, ragi, sesame, green leafy vegetables, eggs, chicken",
      "B12: eggs, dairy, fish, chicken, meat (vegetarians often need supplementation)",
      "Vitamin D: fatty fish, eggs, fortified milk + sunlight",
      "Magnesium: pumpkin seeds, almonds, leafy greens, whole grains",
      "Zinc: pumpkin seeds, chickpeas, cashews, eggs",
      "Vitamin C: amla, citrus fruits, guava (aids iron absorption)",
    ],
    foodsToAvoid: [
      "Tea/coffee within 1 hour of iron-rich meals (blocks absorption)",
      "Excess calcium with iron meals (competition for absorption)",
      "Refined foods (low in micronutrients)",
    ],
    faqs: [
      { q: "Should I just take a multivitamin?", a: "Multivitamins help fill gaps but do not address the underlying dietary patterns. We prefer food-first correction with targeted supplementation where genuinely needed." },
      { q: "I am vegetarian — am I at risk?", a: "Higher risk for B12, iron, vitamin D, omega-3 deficiencies. We design vegetarian plans to maximise these, with supplementation for B12." },
    ],
    related: ["osteoporosis", "osteoarthritis"],
  },

  "water-retention": {
    slug: "water-retention",
    phpPath: "/treatment/water-retention.php",
    title: "Water Retention",
    h1: "Water Retention / Edema Diet in Gurgaon",
    metaTitle: "Water Retention / Edema Diet Plan in Gurgaon | Go Moringa",
    metaDescription: "Diet plan for water retention and edema by Go Moringa — low-sodium, potassium-rich Indian meals, addressing underlying causes.",
    heroImage: "/assets/services/diet.jpg",
    introLead: "Water retention — swelling in feet, ankles, hands, or face — is uncomfortable and often signals an underlying issue. Dietary management addresses the most common causes: excess sodium, low protein, hormonal patterns, and venous/lymphatic issues.",
    aboutCondition: "Edema (water retention) has many causes — high sodium intake, premenstrual hormonal patterns, pregnancy, prolonged sitting/standing, certain medications, kidney issues, heart conditions, low protein intake.",
    howDietHelps: "Reducing sodium intake substantially decreases retention. Increasing potassium counterbalances sodium. Adequate protein prevents the low-albumin edema pattern. Hydration paradoxically helps (dehydration can worsen retention).",
    foodsToInclude: [
      "Potassium-rich: banana, coconut water, leafy greens",
      "Adequate hydration",
      "Adequate protein",
      "Asparagus, celery (natural diuretics)",
      "Cucumber, watermelon (water content)",
    ],
    foodsToAvoid: [
      "Excess salt and salty Indian condiments (papad, achaar, namkeen)",
      "Packaged foods (hidden sodium)",
      "Excess alcohol",
      "Sweetened beverages",
    ],
    faqs: [
      { q: "When should I be worried about water retention?", a: "Sudden swelling, swelling with shortness of breath, or facial swelling with morning weight gain warrants immediate medical evaluation — could indicate kidney, heart, or liver issues." },
    ],
    related: ["high-blood-pressure", "heart-disease"],
  },

  "sleep-apnea-and-respiratory": {
    slug: "sleep-apnea-and-respiratory",
    phpPath: "/treatment/sleep-apnea-and-respiratory.php",
    title: "Sleep Apnea and Respiratory",
    h1: "Sleep Apnea and Respiratory Diet Support",
    metaTitle: "Diet for Sleep Apnea and Respiratory Conditions | Go Moringa",
    metaDescription: "Diet support for sleep apnea and respiratory conditions by Go Moringa — weight management, anti-inflammatory eating, evening meal timing.",
    heroImage: "/assets/treatment/respiratory.jpg",
    introLead: "Sleep apnea and many chronic respiratory conditions respond significantly to weight management and dietary intervention. Even modest weight loss often reduces sleep apnea severity substantially.",
    aboutCondition: "Sleep apnea — repeated breathing pauses during sleep — is strongly associated with obesity, particularly neck circumference. Symptoms include loud snoring, daytime fatigue, morning headaches, mood changes, and high blood pressure.",
    howDietHelps: "Weight loss is the single biggest intervention for sleep apnea. Anti-inflammatory eating helps asthma and inflammation-driven respiratory conditions. Light, early dinners prevent acid reflux that worsens nocturnal symptoms.",
    foodsToInclude: [
      "Anti-inflammatory foods: omega-3 fish, walnuts, flaxseed",
      "Leafy greens (magnesium, antioxidants)",
      "Berries, citrus (vitamin C, antioxidants)",
      "Light, early dinners (reflux prevention)",
    ],
    foodsToAvoid: [
      "Heavy late-night dinners",
      "Alcohol (worsens sleep apnea)",
      "Excess sodium (worsens BP, swelling)",
      "Pro-inflammatory foods: refined carbs, trans fats",
    ],
    faqs: [
      { q: "Will I still need my CPAP if I lose weight?", a: "Often yes, but at lower pressure — significant weight loss reduces apnea events and CPAP requirements. Some clients with moderate apnea become CPAP-independent after weight loss." },
    ],
    related: ["snoring", "weight-loss"],
  },

  snoring: {
    slug: "snoring",
    phpPath: "/treatment/snoring.php",
    title: "Snoring",
    h1: "Diet Support for Snoring and Sleep Quality",
    metaTitle: "Diet for Snoring and Better Sleep | Go Moringa Gurgaon",
    metaDescription: "Diet support for snoring by Go Moringa — weight management, evening eating patterns, alcohol moderation for better sleep.",
    heroImage: "/assets/treatment/snoring.jpg",
    introLead: "Habitual snoring often has dietary contributors — neck weight, evening alcohol, late heavy meals, and reflux. Dietary intervention reduces snoring frequency and intensity in most cases.",
    aboutCondition: "Snoring becomes a clinical concern when it disrupts sleep quality or signals sleep apnea. Risk factors include excess neck weight, nasal congestion, evening alcohol, late heavy dinners, and certain sleeping positions.",
    howDietHelps: "Weight loss (especially neck and abdominal fat), reduced evening alcohol, light early dinners, anti-reflux eating patterns, and adequate hydration all reduce snoring.",
    foodsToInclude: ["Light, early dinners (by 7:30 PM)", "Anti-inflammatory foods", "Adequate hydration during the day"],
    foodsToAvoid: ["Evening alcohol", "Heavy late dinners", "Acid reflux triggers (fried foods, very spicy food at dinner)"],
    faqs: [
      { q: "How much weight loss helps snoring?", a: "Even 5-10 percent body weight reduction often substantially reduces snoring. Neck circumference reduction is the specific metric to track." },
    ],
    related: ["sleep-apnea-and-respiratory", "weight-loss"],
  },

  "certain-medicines": {
    slug: "certain-medicines",
    phpPath: "/treatment/certain-medicines.php",
    title: "Certain Medicines",
    h1: "Diet Support for Medication-Related Issues",
    metaTitle: "Diet Support for Medication Side Effects in Gurgaon | Go Moringa",
    metaDescription: "Diet support by Go Moringa for medication-related weight gain, nutrient depletion, GI side effects — steroids, antidepressants, thyroid medication.",
    heroImage: "/assets/treatment/certain Medicine.jpg",
    introLead: "Many medications cause weight gain, nutrient depletion, or digestive issues. Diet often substantially mitigates these side effects, allowing you to continue the medication while reducing its downside.",
    aboutCondition: "Common medications causing dietary issues: corticosteroids (weight gain, glucose elevation, bone loss), antidepressants (weight gain in some), antipsychotics (significant weight gain, glucose), beta-blockers (slight weight gain), oral contraceptives (varied effects), some anti-epileptics, and many chemotherapy drugs.",
    howDietHelps: "Targeted dietary intervention can mitigate specific side effects — for example, low-glycaemic eating with steroid use, B-vitamin focus with metformin, calcium support with PPI long-term use. We coordinate with your prescribing physician on the specifics.",
    foodsToInclude: [
      "Depends entirely on the specific medication and its side effects",
      "We design plans per case after reviewing your medication list",
    ],
    foodsToAvoid: [
      "Foods that interact with your specific medication (grapefruit with statins, vitamin K with warfarin, etc.)",
    ],
    faqs: [
      { q: "Can I just stop the medication?", a: "Do not make medication changes without your prescribing physician's input. We work with your medication regimen, not against it." },
    ],
    related: ["cushing-syndrome", "diabetes"],
  },
};

export const TREATMENT_LIST = Object.values(TREATMENTS);

export function getTreatment(slug: string): TreatmentData | undefined {
  return TREATMENTS[slug];
}
